<div class="category index intro">
    <div class="inner-site">
        <h1><?=$category->getCategory()?></h1>
        <div class="description">
            <?=$category->getDescription()?>
        </div>
    </div>
</div>

<?php if ($category->getImages()->count()): ?>

<div class="category index images">
    <div class="inner-site">

        <div class="gallery">

        <?php foreach ($category->getImages() as $image): ?>



            <?=$this->tag->linkTo(
                array(
                    $image->getResizedSrc(800),
                    $this->tag->image($image->getResizedSrc(250), array
                    (
                        'alt' => $category->getCategory(),
                    )),
                    'class' => 'fancybox',
                )
            ) . PHP_EOL ?>


        <?php endforeach ?>

        </div>

    </div>
</div>

<?php endif ?>

<?php if ($category->getDestinations()->count()): ?>

<div class="category index destinations-list">

    <div class="inner-site">
        <h2><strong><?=$category->getCategory()?></strong> - destinacije</h2>

        <ul>
            <?php foreach ($category->getDestinations() as $destination): ?>

            <li class="clearfix">

                <?php if ($destination->getMainImage()): ?>

                <div class="image">
                    <?=$this->tag->linkTo(array
                    (
                        $destination->getUri(),
                        $this->tag->image(array
                        (
                            $destination->getMainImage()->getResizedSrc(250)
                        ))
                    )) . PHP_EOL ?>
                </div>

                <?php endif ?>

                <div class="description">
                    <h3><strong><?=$this->tag->linkTo($destination->getUri(), $destination->getDestination())?></strong> <span>/ Broj ponuda: <?=$destination->packages->count()?></span></h3>
                    <div class="description-text">
                        <?=$destination->getShortDescription()?>
                    </div>
                    <div class="link">

                        <?=$this->tag->linkTo($destination->getUri(), '/ Pogledajte ponude /') . PHP_EOL?>
                    </div>
                </div>
            </li>

            <?php endforeach ?>

        </ul>
    </div>

</div>

<?php endif ?>