<div class="category index intro">
    <div class="inner-site">
        <h1><?=$category->getCategory()?></h1>
        <div class="description">
            <?=$category->getDescription()?>
        </div>
    </div>
</div>

<?php if ($category->getImages()->count()): ?>

<div class="category index images">
    <div class="inner-site">
        <?=$this->partial('partials/no-caption-slider-image-gallery', array(
           'item' => $category,
        ))?>
    </div>
</div>

<?php endif ?>

<?php if ($category->getDestinations()->count()): ?>

<div class="category index destinations-list">

    <div class="inner-site">
        <h2><strong><?=$category->getCategory()?></strong> - destinacije</h2>

        <ul>
            <?php foreach ($category->getDestinations() as $destination): ?>

            <li>

                <?php if ($destination->getMainImage()): ?>

                <div class="image">
                    <a href="<?=$destination->getUri()?>"><?=$this->tag->image(array($destination->getMainImage()->getResizedSrc(250)))?></a>
                </div>

                <?php endif ?>

                <div class="description">
                    <h3><strong><a href="<?=$destination->getUri()?>"><?=$destination->getDestination()?></a></strong> <span>/ Broj ponuda: <?=$destination->getPackages()->count()?></span></h3>
                    <div class="description-text">
                        <?=$destination->getShortDescription()?>
                    </div>
                    <div class="link">

                        <a href="<?=$destination->getUri()?>">/ Pogledajte ponude /</a>
                    </div>
                </div>
            </li>

            <?php endforeach ?>

        </ul>
    </div>

</div>

<?php endif ?>
