<div class="destination index intro">
    <div class="inner-site">
        <h1><?=$destination->getDestination()?></h1>
        <div class="description">
            <?=$destination->getDescription()?>
        </div>
    </div>
</div>

<?php if ($destination->getImages()->count()): ?>

<div class="destination index images">
    <div class="inner-site">
        <?=$this->partial('partials/no-caption-slider-image-gallery', array(
                'item' => $destination,
            ))?>
    </div>
</div>

<?php endif ?>

<?php if ($destination->getPackages()->count()): ?>

    <div class="destination index packages-list">

        <div class="inner-site">
            <div>
                <label for="type" style="font-weight:bold"></label>
                <?=$this->tag->selectStatic(
                    array(
                        'type',
                        array(
                            1 => 'Apartmani',
                            2 => 'Hoteli',
                        ),
                        'useEmpty' => true,
                        'emptyText' => 'Filtraj aranžmane!',
                        'id' => 'packages-selector',
                        'class' => 'customSelect'
                    )
                ) . PHP_EOL;
                ?>
            </div>

            <ul>
                <?php foreach ($destination->getPackages($type) as $package): ?>

                    <li class="clearfix">

                        <?php if ($package->getMainImage()): ?>

                            <div class="image">
                                <?=$this->tag->linkTo(array
                                    (
                                        $package->getUri(),
                                        $this->tag->image(array
                                        (
                                            $package->getMainImage()->getResizedSrc(250)
                                        ))
                                    )) . PHP_EOL ?>
                            </div>

                        <?php endif ?>

                        <div class="description">
                            <h3><strong><?=$this->tag->linkTo($package->getUri(), $package->getPackage())?></strong></h3>
                            <div class="description-text">
                                <?=$package->getShortDescription()?>
                            </div>
                            <div class="link">

                                <?=$this->tag->linkTo($package->getUri(), '/ Pogledajte aranžman /') . PHP_EOL?>
                            </div>
                        </div>
                    </li>

                <?php endforeach ?>

            </ul>
        </div>

    </div>

<?php endif ?>
