<ul class="nav navbar-nav">
    <li><a href="<?=$this->url->get(array('for' => 'admin', 'controller' => 'index', 'action' => 'dashboard'))?>">Kontrolna strana</a></li>
    <li><a href="<?=$this->url->get(array('for' => 'admin', 'controller' => 'category', 'action' => 'index'))?>">Kategorije</a></li>
    <li><a href="<?=$this->url->get(array('for' => 'admin', 'controller' => 'destination', 'action' => 'index'))?>">Destinacije</a></li>
    <li><a href="<?=$this->url->get(array('for' => 'admin', 'controller' => 'package', 'action' => 'index'))?>">Aranzmani</a></li>
    <li><?=$this->tag->linkTo(array
    (
        array
        (
            'for' => 'admin',
            'controller' => 'index',
            'action' => 'logout',
        ),
        'Log out',
    )) . PHP_EOL ?>
    </li>
</ul>