<ul class="nav">
    <li><a href="<?=$this->url->get(array('for' => 'admin', 'controller' => 'index', 'action' => 'dashboard'))?>">Kontrolna strana</a></li>
    <li><a href="<?=$this->url->get(array('for' => 'admin', 'controller' => 'category', 'action' => 'index'))?>">Kategorije</a></li>
    <li><a href="<?=$this->url->get(array('for' => 'admin', 'controller' => 'destination', 'action' => 'index'))?>">Destinacije</a></li>
</ul>