
<div class="admin index dashboard">
    <dl>
        <dt><h4>Kategorije</h4></dt>
        <dd>
            <ul>

                <?php foreach($categories as $category): ?>

                <li><a href="<?=$category->getUpdateUrl()?>"><?=$category->getCategory()?></a></li>

                <?php endforeach ?>

                <li><a href="<?=$this->url->get(array('for' => 'admin', 'controller' => 'category', 'action' => 'create'))?>">Dodaj novu kategoriju</a></li>

            </ul>
        </dd>
    </dl>
</div>