
<div class="admin index dashboard">
    <ul>
        <li class="section">
            <h4><a style="color:black" href="<?=$this->url->get('admin/category/index')?>">Kategorije</a></h4>

            <ul>

                <?php foreach ($categories as $category): ?>

                <li><a href="<?=$category->getUpdateUrl()?>"><?=$category->getCategory()?></a></li>

                <?php endforeach ?>

                <li class="action"><a href="<?=$this->url->get(array('for' => 'admin', 'controller' => 'category', 'action' => 'create'))?>">Dodaj novu kategoriju</a></li>

            </ul>
        </li>

        <li class="section">
            <h4><a style="color:black" href="<?=$this->url->get('admin/destination/index')?>">Destinacije</a></h4>

            <ul>
                
                <?php foreach ($destinations as $destination): ?>
                
                <li><a href="<?=$destination->getUpdateUrl()?>"><?=$destination->getDestination()?></a></li>
                
                <?php endforeach ?>
                
                <li class="action"><a href="<?=$this->url->get(array('for' => 'admin', 'controller' => 'destination', 'action' => 'create'))?>">Dodaj novu destinaciju</a></li>
            </ul>
        </li>

        <li class="section">
            <h4><a style="color:black" href="<?=$this->url->get('admin/package/index')?>">Aranzmani</a></h4>

            <ul>
                
                <?php foreach ($packages as $package): ?>
                
                <li><?=$this->tag->linkTo(array
                (
                    array
                    (
                        'for' => 'admin-update',
                        'controller' => 'package',
                        'action' => 'update',
                        'id' => $package->getPackageId(),
                    ),
                    $package->getPackage(),
                ));?></li>
                
                <?php endforeach ?>
                
                <li class="action"><?=$this->tag->linkTo(array
                (
                    array
                    (
                        'for' => 'admin',
                        'controller' => 'package',
                        'action' => 'create',
                    ),
                    'Dodaj novi aranzman'
                ))?></li>
                
            </ul>
        </li>
        <li class="section">
            <h4>Akcije</h4>

            <ul>
                <li class="action">
                    <?=$this->tag->linkTo(array(
                    'admin/index/sortTaggedPackages',
                    'Postavi prioritete',
                )) . PHP_EOL ?>
                </li>


                <li class="action">
                    <?=$this->tag->linkTo(array(
                    'admin/index/agents',
                    'Cenovnici za agente',
                )) . PHP_EOL ?>
                </li>

                <li class="action">
                    <?=$this->tag->linkTo(array(
                        'admin/page/index',
                        'Stranice',
                    )) . PHP_EOL ?>
                </li>

                <li class="action">
                    <?=$this->tag->linkTo(array(
                        'admin/index/cover',
                        'Izmena naslovne',
                    )) . PHP_EOL ?>
                </li>

                <li class="action logout">
                    <?=$this->tag->linkTo(array(
                    'admin/index/logout',
                    'Logout',
                )) . PHP_EOL ?>
                </li>
            </ul>
        </li>
    </ul>
</div>