
<div class="admin index dashboard">
    <dl>
        <dt><h4>Kategorije</h4></dt>
        <dd>
            <ul>

                <?php foreach ($categories as $category): ?>

                <li><a href="<?=$category->getUpdateUrl()?>"><?=$category->getCategory()?></a></li>

                <?php endforeach ?>

                <li><a href="<?=$this->url->get(array('for' => 'admin', 'controller' => 'category', 'action' => 'create'))?>">Dodaj novu kategoriju</a></li>

            </ul>
        </dd>
        <dt><h4>Destinacije</h4></dt>
        <dd>
            <ul>
                
                <?php foreach ($destinations as $destination): ?>
                
                <li><a href="<?=$destination->getUpdateUrl()?>"><?=$destination->getDestination()?></a></li>
                
                <?php endforeach ?>
                
                <li><a href="<?=$this->url->get(array('for' => 'admin', 'controller' => 'destination', 'action' => 'create'))?>">Dodaj novu destinaciju</a></li>
            </ul>
        </dd>
        <dt><h4>Aranzmani</h4></dt>
        <dd>
            <ul>
                
                <?php foreach ($packages as $package): ?>
                
                <li><?=$this->tag->linkTo(array
                (
                    array
                    (
                        'for' => 'admin-update',
                        'controller' => 'package',
                        'action' => 'update',
                        'id' => $package->getPackageId(),
                    ),
                    $package->getPackage(),
                ));?></li>
                
                <?php endforeach ?>
                
                <li><?=$this->tag->linkTo(array
                (
                    array
                    (
                        'for' => 'admin',
                        'controller' => 'package',
                        'action' => 'create',
                    ),
                    'Dodaj novi aranzman'
                ))?></li>
                
            </ul>
        </dd>
        <dt><h4>Prioriteti</h4></dt>
        <dd>
            <ul>
                <li><?=$this->tag->linkTo(array(
                    'admin/index/sortTaggedPackages',
                    'Postavi prioritete',
                )) . PHP_EOL ?>
                </li>
            </ul>
        </dd>
    </dl>
</div>