<div class="info-page">
    <div class="inner-site">
        <h1>Putna dokumenta</h1>
        <div class="static-page">
            <p dir="ltr">
                PUTNA DOKUMENTA
            </p>
            <p dir="ltr">
                Svaki putnik je u obavezi da poseduje važeću putnu ispravu – pasoš (kopija stranice sa ličnim podacima se dostavlja agenciji). Deca koja putuju zajedno sa
                roditeljima treba takođe da poseduju svoj važeći pasoš. Agencija Robinson ne snosi odgovornost za neispravnu putnu dokumentaciju, ne dobijanje vize za
                kategoriju građana kojima je viza potrebna, kao i u slučaju da pogranične vlasti onemoguće putniku ulaz na teritoriju EU, u tom slučaju će se smatrati da
                je putnik odustao od aranžmana i postupiće se prema Opštim uslovima putovanja agencije Robinson.
            </p>
            <p dir="ltr">
                Preporučujemo putnicima koji poseduju biometrijske pasoše da se o uslovima putovanja i boravka u EU (potrebna novčana sredstva za boravak, zdravstveno
                osiguranje, potvrde o smeštaju...) informišu u ambasadama zemlje u koje putuju ili na www.europa.rs. Više informacija o ukidanju viznog režima i uslovima
                boravka u EU možete dobiti I na našem sajtu <a href="http://www.robinson.rs">www.robinson.rs</a>.
            </p>
            <br/>
            <p dir="ltr">
                Dokument kojim se putnici smeštaju u smeštajni objekat jeste uputnica ili Vaučer koji se dobija nakon celokupne uplate aranžmana u agenciji. Za kružne ture
                i grupna putovanja iz našeg programa, vaučer za grupu predaje vodič - predstavnik agencije.
            </p>
            <br/>
            <p dir="ltr">
                Ukoliko maloletno lice putuje bez pratnje roditelja, roditelji su u obavezi da daju saglasnost o prelasku granice samostalno ili u pratnji jednog roditelja
                ukoliko putuje sa jednim roditeljem.
            </p>
            <div>
                <br/>
            </div>
        </div>
    </div>
</div>