<div id="index-index">
    <div class="inner-site">

        <?php if ($lastMinutePackages->count()): ?>

        <div id="index-last-minute">
            <h4><strong>Last minute</strong> ponude</h4>

            <?php foreach ($lastMinutePackages as $package): ?>

                <?=$this->partial(
                    'partials/index-package-item',
                    array('package' => $package)
                ) . PHP_EOL ?>

            <?php endforeach ?>

        </div>

        <?php endif ?>

        <div id="index-first-section" class="index section tabs">
            <ul>
                <li><a href="#tab1" class="selected">Poslednje objave</a></li>
                <li><a href="#tab2">Popularni aranžmani</a></li>
            </ul>
            <div id="tab1">

                <?php foreach ($latestPackages as $package): ?>

                    <?=$this->partial(
                        'partials/index-package-item',
                        array('package' => $package)
                    ) . PHP_EOL ?>

                <?php endforeach ?>

            </div>
            <div id="tab2">

                <?php foreach ($popularPackages as $package): ?>

                <?=$this->partial(
                        'partials/index-package-item',
                        array('package' => $package)
                ) . PHP_EOL ?>

                <?php endforeach ?>

            </div>
        </div>

        <div id="index-category-tabs-section" class="index section tabs">
            <ul>
                <?php foreach ($tabs as $key => $tab): ?>

                    <li><a href="#category-tab-<?=$key?>"><?=$tab->name?></a></li>
                <?php endforeach ?>
            </ul>

            <?php foreach ($tabs as $key => $tab): ?>

            <div class="category-tab" id="category-tab-<?=$key?>">

                <div class="cat-preview">

                    <?php if (isset($tab->category->images[0])): ?>

                    <div class="cat-thumb">
                        <?=\Phalcon\Tag::image($tab->category->images[0]->getResizedSrc()) . PHP_EOL ?>
                    </div>
                    <?php endif ?>
                </div>

                <div class="cat-text">

                    <?=$tab->category->getDescription(200) . PHP_EOL ?>
                </div>

            </div>

            <?php endforeach ?>

        </div>

    </div>
</div>
