<div class="info-page">
    <div class="inner-site">
        <h1>Korisne informacije</h1>
        <div class="static-page">
            <p dir="ltr">
                KORISNE INFORMACIJE
            </p>
            <br/>
            <p dir="ltr">
                PREVOZ
            </p>
            <br/>
            <p dir="ltr">
                AUTOBUSKI PREVOZ se obavlja komfornim iznajmljenim autobusima ovlašćenih prevoznika sa audio i video opremom kao i sa klimom. Sedišta u autobusu se
                određuju isključivo po redosledu prijave, izuzetno se porodicama sa malom decom može izaći u susret. Sedišta su podložna promeni usled promene tipa i broja
                autobusa kao i usled promene brojnog stanja putnika za odgovarajuće putovanje. Svi autobusi napred imaju istaknutu tablu sa natpisom ROBINSON. Tokom vožnje
                autobusom pušenje nije dozvoljeno. U toku putovanja se pravi dovoljan broj pauza. Putnici sami snose troškove osveženja i usluga toaleta. Vrednosti kao što
                su novac, nakit, skupoceni parfemi i drugo moraju isključivo biti u ručnom prtljagu. Putnici sami vode računa o ličnom i
            </p>
            <p dir="ltr">
                ručnom prtljagu i odgovaraju za isti. Zbog učestalih kređa na mestu polaska posebno skrećemo pažnju da se putnici obraćaju isključivo službenim licima
                agencije Robinson i postupaju po njihovim uputstvima oko pakovanja prtljaga u autobus.
            </p>
            <br/>
            <p dir="ltr">
                AVIONSKI PREVOZ se obavlja ČARTER LETOM mimo redovnog saobraćaja što snižava cenu ali nekad može doći do korekcije predviđenog vremena poletanja od strane
                avio kompanije. Putnici su dužni da dva dana pre poletanja u agenciji Robinson provere predviđeno vreme leta. Neophodno je da se putnici na dan putovanja
                prijave na istaknuti šalter agencije Robinson najmanje 2 sata pre poletanja aviona kako bi preuzeli putna dokumenta (karte, pasoše i dr.) i mogli da se
                prijave na
            </p>
            <p dir="ltr">
                šalteru avio prevoznika ili agencije Robinson. Skoro na svim letovima je okvirna dozvoljena težina prtljaga 20 kilograma. U slučaju gubitka prtljaga
                putnici se na ciljnom aerodrumu obraćaju službi za izgubljeni prtljag. O putnicima na aerodromu i u avionu, isključivo brinu ovlašćena lica avioprevoznika
                i aerodroma - stjuardese.
            </p>
            <br/>
            <p dir="ltr">
                SOPSTVENI PREVOZ podrazumeva da putnici sami organizuju prevoz do turističke destinacije avionom, vozom, autobusom ili najčešće sopstvenim automobilom i to
                nije predmet ugovora između putnika i agencije. Putnici su dužni da se sami upoznaju sa saobraćajnim propisima tranzitne i odredišne zemlje i da sami brinu
                i odgovaraju za prevozno sredstvo. Putnici sami snose konsekvence ukoliko prilikom sopstvenog prevoza kasne na početak uplaćenog aranžmana i nemaju pravo
                na refundaciju za neiskorišćene usluge. Predstavnik agencije na dan smene iz tehničkih razloga nije u mogućnosti da lično smesti putnike sa sopstvenim
                prevozom, već im stoji na raspolaganju informativno telefonom (osim u slučaju nemogućnosti putnika da pronađu smeštaj).
            </p>
            <br/>
            <br/>
            <p dir="ltr">
                SMEŠTAJ
            </p>
            <p dir="ltr">
                Putnik preuzima obavezu upoznavanja i poštovanja pravila ponašanja u određenom smeštajnom objektu koja se odnose na deponovanje vrednosti i novca, unos
                hrane i pića, poštovanja kućnog reda, broj osoba u smeštaju i sl. Agencija ne može biti odgovorna za štete i posledice nastale nepoštovanjem ovih propisa i
                pravila. Ako drugačije nije dogovoreno, smeštaj putnika u objekat ne može biti pre 14:00h na dan početka korišćenja usluge a napuštanje objekta je
                najkasnije u 10:00h na dan
            </p>
            <p dir="ltr">
                završetka korišćenja usluge. Putnici u ceni aranžmana imaju uključen navedeni broj noćenja a ne dana. Nekada usled večernjeg leta i vremena potrebnog za
                transfer putnici se smeštaju u objekat u kasnim noćnim satima.
            </p>
            <br/>
            <br/>
            <p dir="ltr">
                KLIMATSKI USLOVI
            </p>
            <p dir="ltr">
                Za sve destinacije u srednje-evropskim zemljama je klima pretežno slična kao i kod nas. U Mediteranskim zemljama temperatura tokom letnjih meseci može biti
                izuzetno visoka pa vam preporučujemo da koristite zaštitne kreme sa visokim UV faktorom. Posebno obratite pažnju na decu i tokom prvih dana boravka.
                Putnici su dužni da sami pribave zaštitne kreme i sredstva protiv komaraca kako bi sprečili posledice od alergije i sl.
            </p>
            <br/>
            <br/>
            <p dir="ltr">
                VODA
            </p>
            <p dir="ltr">
                Bez obzira na ispravnost vode iz lokalnog vodovoda preporučujemo korišćenje flaširane vode koju gosti sami nabavljaju u lokalnim prodavnicama. Posledice
                mogu nastati usled promene vremenskih prilika i nenaviknutosti na osobine lokalne pitke vode. Voda je higijenski ispravna za upotrebu. Posebno vodite
                računa kada u letnjim mesecima na ostrvima eventualno dođe do povremene nestašice vode, da tu vodu prvo vreme nakon dolaska ne koristite. Dešava se da bude
                slankasta.
            </p>
            <br/>
            <br/>
            <p dir="ltr">
                BORAVAK I FAKULTATIVNI IZLETI
            </p>
            <p dir="ltr">
                Za ugodan boravak i pružanje svih informacija pobrinuće se naš vodičpredstavnik u regiji ili gradu u kojem boravite. Eventualne nedostatke u smeštaju ili
                drugim plaćenim uslugama neophodno je odmah prijaviti predstavniku agencije Robinson kako bi u što kraćem roku bili otklonjeni. Eventualne žalbe je
                neophodno dostaviti vodiču-predstavniku isključivo u pismenoj formi u mestu boravka. Naknadne žalbe se neće uzeti u razmatranje. Najam automobila i
                fakultativni izleti su posebni programi koje organizuju
            </p>
            <p dir="ltr">
                ino – partneri agencije Robinson i nisu sastavni deo ugovora. Vodiči – predstavnici jedino su posrednici u zaključivanju ugovora
            </p>
            <p dir="ltr">
                između naših gostiju i ino – partnera, organizatora. To mogu biti autobuski i brodski izleti, razni obilasci i kulturni i zabavni programi. Opis izleta sa
                cenama dobićete od naših vodiča – predstavnika u mestu boravka. Cene nekada zavise od broja učesnika i sezone. Fakultativni izleti se najčešće izvode na
                srpskom jeziku izuzetno kod malog broja prijavljenih na engleskom jeziku. Agencija Robinson nije organizator ovih usluga.
            </p>
            <br/>
            <br/>
            <br/>
            <p dir="ltr">
                LEGENDA ZA CENOVNIKE:
            </p>
            <br/>
            <p dir="ltr">
                St 02 – dvokrevetni studio NA – najam studia/ apartmana
            </p>
            <p dir="ltr">
                St 03 – trokrevetni studio ND – noćenje sa doručkom
            </p>
            <p dir="ltr">
                St 04 – četvorokrevetni studio PP - polupansion
            </p>
            <p dir="ltr">
                App 02 – dvokrevetni apartman PA - pun pansion
            </p>
            <p dir="ltr">
                App 03 – trokrevetni apartman AL – sve uključeno
            </p>
            <p dir="ltr">
                App 04 – četvorokrevetni apartman PL – pomoćni ležaj
            </p>
            <p dir="ltr">
                App 05 – petokrevetni apartman STAND – standardna soba
            </p>
            <p dir="ltr">
                1/2- dvokrevetna soba SUP/SUPER – superior soba
            </p>
            <p dir="ltr">
                1/3- trokrevetna soba JUN APP – junior apartman
            </p>
            <p dir="ltr">
                2+2 soba – dvokrevetna soba sa krevetima na sprat FAMILY APP. – porodični apartman
            </p>
            <p dir="ltr">
                1/4 soba - četvorokrevetna soba SV - pogled more
            </p>
            <p dir="ltr">
                A/C - klima SSV - bočni pogled more
            </p>
            <div>
                <br/>
            </div>
        </div>
    </div>
</div>