<div class="info-page">
    <div class="inner-site">
        <h1>Nismo našli stranu! :(</h1>
        <div class="static-page">
            <p>
                Nažalost, nismo mogli da nadjemo stranu koju ste tražili. <br />
                Preporučujemo da odete na <a style="text-decoration: underline" href="/">početak našeg sajta</a>, odatle bi trebalo da možete lako naći sve što vas zanima. <br />
                Ukoliko ipak ne nađete potrebnu informaciju, preporučujemo da nas kontaktirate preko <a href="/index/contact">kontakt strane</a> i ubrzo ćemo vam se javiti. <br />
                Vaš Robinson vam se zahvaljuje na poverenju!
            </p>
        </div>
    </div>
</div>