<div class="info-page">
    <div class="inner-site">
        <h1>Putno osiguranje</h1>
        <div class="static-page">
            <p dir="ltr">
                PUTNO OSIGURANJE
            </p>
            <br/>
            <p dir="ltr">
                Za sva putovanja u EU obavezno je da za sebe i svoju porodicu pribavite neko od važećih međunarodnih zdravstvenih osiguranja kako bi vaš boravak bio
                bezbrižniji i u slučaju lekarske potrebe povoljniji. Turistička agencija Robinson ima ugovor sa Dunav osiguranjem i u saradnji sa Coris Assistance-om
                omogućava povoljne uslove zaključenja ugovora o međunarodnom zdravstvenom osiguranju. Po uslovima Dunav osiguranja putnici su u obavezi da pozivom call
                centra obaveste osiguravača
            </p>
            <p dir="ltr">
                o medicinskoj intervenciji, i po povratku kući će refundirati troškove iznad unapred utvrđenog iznosa franšize.
            </p>
            <div>
                <br/>
            </div>
        </div>
    </div>
</div>