<div class="info-page">
    <div class="inner-site">
        <h1>Način plaćanja</h1>
        <div class="static-page">
            <p dir="ltr">
                USLOVI I NAČIN PLAĆANJA:
            </p>
            <br/>
            <p dir="ltr">
                Plaćanje se vrši isključivo u dinarskoj protivvrednosti po prodajnom kursu MARFIN BANKE za efektivu na dan uplate.
            </p>
            <br/>
            <p dir="ltr">
                • Gotovinski - rezervacija se vrši uplatom akontacije u iznosu od 40% od ukupne cene aranžmana, a ostatak najkasnije 15 dana
            </p>
            <p dir="ltr">
                pre polaska.
            </p>
            <br/>
            <p dir="ltr">
                • Čekovima građana - prilikom rezervacije 40%, a ostatak deponovanim čekovima na jednake rate do 15. decembra (bez
            </p>
            <p dir="ltr">
                promotivnih popusta, ali i bez obračunavanja kamate).
            </p>
            <br/>
            <p dir="ltr">
                • Kreditom poslovnih banaka po uslovima koje određuje banka prema klijentu, a na osnovu predračuna koji se dobija u
            </p>
            <p dir="ltr">
                agenciji. Prilikom prijave uplaćuje se depozit od 20% ukupne vrednosti aranžmana koji se vraća po odobravanju kredita (uplata
            </p>
            <p dir="ltr">
                punog iznosa od strane banke).
            </p>
            <br/>
            <p dir="ltr">
                • Platnim karticama ili revolving karticama (mogućnost odloženog plaćanja)
            </p>
            <br/>
            <br/>
        </div>
    </div>
</div>