<div class="info-page">
    <div class="inner-site">
        <h1>Dozvoljeni prtljag</h1>
        <div class="static-page">
            <pre style="overflow: hidden">
                Procedura predaje prtljaga

Predati ili registrovani prtljag je prtljag koji predajete na prevoz na šalteru za prijavu putnika i

prtjaga. Predati prtljag prevozi se u prtljažniku aviona i nije Vam dostupan tokom leta.

Ukoliko se na let prijavljujete po dolasku na aerodrom, na šalteru predviđenom za registraciju

putnika avio-kompanije kojom putujete, predajete prtljag koji želite da prijavite na prevoz.

Ukoliko se na let prijavljujete putem interneta, mobilnog telefona ili na kioscima, prtljag

predajete na označenim šalterima za brzu predaju prtljaga. Prilikom prijave prtljaga dobijate

potvrdu u vidu nalepnice da ste prtljag predali na prevoz.

Većina avio-kompanija omogućuje prevoz predatog prtljaga bez naplate, dok se na letovim

određenih avio-kompanija svaki prtljag, izuzev ručnog, posebno naplaćuje.

Kod avio-kompanija koje omogućuju prevoz predatog prtljaga koji ne podleže dodatnoj naplati,

dozvoljena težina varira u zavisnosti od avio kompanije, destinacije i klase prevoza.

Većina avio-kompanija primenjuju pravilo prevoza prtljaga koje podrazumeva da se za putnike

poslovne klase na let mogu predate do 2 komada prtljaga bez dodatne naplate, težine do 32kg,

a za putnike ekonomske klase 1 komad prtljaga bez dodatne naplate, težine do 20 ili 23kg.

Kod čarter letova moguće je PONDERISATI ili spojiti prtljag za dve do tri osobe koje

putuju zajedno, dakle 2-3 osobe puta 23kg u nekoliko prtljaga stim da nijedan nesme da

prekoraci 30kg.

Dozvoljeni ručni prtljag je do 8 kg. Svaki visak prtljaga će se naplaćivati prilikom predaje

po 6 € po kilogramu u dinarskoj protivvrednosti na šalteru aerodruma.

Precizne podatke u vezi sa politikom prevoza predatog prtljaga, ograničenjima u težini i ukupnoj

količini predatog prtljaga možete dobiti prilikom kupovine avionske karte ili po dolasku na

aerodrom, kod predstavnika avio-kompanije za čiji let ste kupili avionsku kartu.

U prtljagu nije dozvoljeno nositi predmete koji se smatraju opasnim materijama.

Višak prtljaga

Ukoliko Vaš prtljag prelazi propisane težine ili količinu, prevoz viška prtljaga avio-kompanije

dodatno naplaćuju. Cenu prevoza viška prtljaga određuje svaka avio-kompanija zasebno.

Informacije o iznosima koji se primenjuju prilikom prevoza viška prtljaga možete dobiti u

izabranoj avio-kompaniji.

Specijalni i prtljag nestandardne veličine

Avio-kompanije najčešće prihvataju prevoz sportske opreme, muzičkih instrumenata, kućnih

ljubimaca, lomljivih i skupocenih stvari, kao i predmeta veće težine ili dimenzija pod posebnim

uslovima. Kako je za prevoz određenih predmeta ponekada potrebna saglasnost avio-kompanije,

prevoz ovakvih stvari ili predmeta potrebno je prijaviti avio-kompaniji već prilikom pravljenja

rezervacije.

Predimenzionisani prtljag prijavljuje se na šalteru za prijavu putnika i prtljaga na let, a predaje na

posebnom šalteru, čiju lokaciju možete pogledati ovde.

Informacije u vezi sa mogućnostima, načinom i cenovnikom prevoza specijalnog i prtljaga

nestandardne veličine (predimenzionisanog prtljaga) možete dobiti u izabranoj avio-kompaniji.

Korisni saveti

Identifikacija

Iz bezbednosnih razloga ili u slučaju gubitka prtljaga, korisno je da Vaš prtljag sa spoljašnje

strane bude označen nalepnicom sa Vašim ličnim i kontakt podacima (ime, prezime, kontakt

telefon i adresa).

Lomljive stvari

Savetujemo da Vaš prtljag bude bezbedno upakovan. Upakujte sve stvari koje sadrže tečnosti u

zasebne plastične kese, kako se tečnost ne bi izlila po sadržaju u torbi u slučaju lomljenja. Više

informacija u vezi sa prevozom lomljivih stvari možete dobiti u izabranoj avio-kompaniji.

Tokom boravka na aerodromu

• Svoj prtljag, zaključan, obeležen nalepnicom ili priveskom sa imenom i adresom,

nemojte ostavljati bez nadzora do predaje na šalteru za registraciju putnika.

• Savetujemo Vam da ručni prtljag koji unosite sa sobom u putničku kabinu bude pod

vašim stalnim nadzorom.

• Savetujemo Vam da ne preuzimate i ne predajete tuđ prtljag kao svoj, zbog stvari koje bi

Vam mogle ugroziti bezbednost ili Vas izložiti zakonskoj odgovornosti.

• Avio-kompanije savetuju da vredne stvari prevozite u ručnom (predatom) prtljagu.
            </pre>
        </div>
    </div>
</div>