<div class="info-page">
    <div class="inner-site">
        <div class="static-page">
            <h1>Opšti uslovi putovanja</h1>

            <p dir="ltr">
                Na osnovu člana 56. Zakona o turizmu („Sl. glasnik RS“ br. 36/2009, 88/2010, 99/2011 i 93/2012) direktor TA “ROBINZON DOO“ iz Beograda, dana 01.06.2014
                god. utvrđuje sledeće:
            </p>
            <br/>
            <p dir="ltr">
                OPŠTE USLOVE PUTOVANJA
            </p>
            <p dir="ltr">
                1 PREDUGOVORNO OBAVEŠTAVANJE:
            </p>
            <p dir="ltr">
                Potpisivanjem standardnog ugovora-potvrde-prijave o putovanju (dalje: Ugovor) svojim potpisom u ime svih putnika iz Ugovora (dalje: Putnik) potvrđuje da su
                mu uručeni ovi Opšti uslovi putovanja (dalje: Opšti uslovi), unapred pripremljen i objavljen program putovanja (dalje: Program), da je kao i svi putnici iz
                ugovora se istima upoznat i da ih u celosti prihvata, kao i da je upoznat sa fakultativnim mogućnostima putnog osiguranja. Odredbe ovih Opštih uslova čine
                sastavni deo Ugovora između Putnika i TA “ Robinzon doo” kao organizatora putovanja (dalje: Organizator) i obavezujuće su za obe ugovorne strane, osim
                odredbi definisanih posebnim pisanim ugovorom ili Programom. Pre zaključivanja Ugovora, Organizator može u svako doba izmeniti opis svojih usluga u
                Programu. Putnik i Organizator saglasno konstatuju da je pre zaključenja Ugovora Putnik o svim eventualnim promenama podataka iz Programa u primerenom roku
                obavešten pre zaključenja Ugovora. U slučaju postojanja razlike između prijave Putnika i izmenjenog predloga Organizatora, novi Program se smatra novim
                predlogom i obavezuje Organizatora narednih 48 časova. Ukoliko Putnik ne obavesti Organizatora u navedenom roku da ne prihvata novoučinjeni Program -
                ponudu, Ugovor se smatra raskinutim.
            </p>
            <p dir="ltr">
                2. PRIJAVE, UPLATE I UGOVOR:
            </p>
            <p dir="ltr">
                Prijavu Putnik dostavlja pismenim putem ili na trajnom nosaču zapisa ili putem e-maila ili faksa. Putnik se za putovanje može prijaviti u sedištu,
                ograncima, odnosno izdvojenim posebnim prostorima Organizatora, kao i u turističkim agencijama koje imaju sa Organizatorom zakljčen Ugovor o posredovanju
                (dalje: Posrednik). Kada Posrednik u Programu Organizatora i Ugovoru sa Putnikom ne naznači svoje svojstvo Posrednika, Organizator ne odgovara za izvršenje
                Programa prema Putniku, već je to obaveza Posrednika. Prijava Putnika postaje punovažna kada je potvrđena zaključenjem Ugovora na način na koji je Prijava
                učinjena i uplatom akontacije u visini od 50% od cene aranžmana. Ostatak ugovorene cene, ako drugačije nije ugovoreno, plaća se 15 dana pre početka
                putovanja. Ukoliko Putnik, u roku ne izvrši uplatu u celosti, smatra se da je putovanje otkazao u skladu sa tačkom 12. Opštih uslova. Svaka uplata
                akontacije vodi se kao uplata za sve putnike, a ne samo za jednog određenog putnika iz Ugovora. Zaključenjem Ugovora, Program (prethodno objavljen ili
                naknadno izmenjen) postaje njegov sastavni deo i ne može se menjati, osim ako ugovorne strane izričito ugovore drugačije ili ako promene nastanu usled više
                sile. Ukoliko dođe do otkaza ili izmena Ugovora, otkazne odredbe i izmene važe za sve navedene putnike u Ugovoru. Za blagovremenost uplate merodavan je
                datum uplate na račun Organizatora ili Posrednika. U slučaju neblagovremene uplate u celosti, avansnog plaćanja ili plaćanja preostalog dela uplate
                aranžmana, Organizator putovanja može odustati od Ugovora i tražiti nadoknadu u skladu sa tačkom 12. ovih Opštih uslova.
            </p>
            <p dir="ltr">
                3. OBAVEZA I PRAVA ORGANIZATORA:
            </p>
            <p dir="ltr">
                - U Ugovoru osim usluga iz Programa unese posebne zahteve putnika sa kojima se isključivo Organizator saglasio, - Isplati srazmernu realnu razliku između
                ugovorene cene i cene putovanja snižene srazmerno neizvršenju ili nepotpunom izvršenju Ugovora (dalje: Sniženje cene) povodom blagovremene i osnovane
                pisane reklamacije - prigovora Putnika u skladu sa zakonom i ovim Opštim uslovima, osim ako su propusti u izvršenju Ugovora nastali: krivicom Putnika ili
                se pripisuju trećem licu koje nije bilo ugovoreni neposredni pružalac usluga u realizaciji Programa, delovanjem više sile ili nepredviđenih događaja na
                koje Organizator nema uticaja i čije su posledice neizbežne uprkos primeni dužne pažnje ili nekim drugim događajima koje Organizator nije mogao predvideti
                i prevladati, - Saglasno dobrim poslovnim običajima u ovoj oblasti da se stara o pravima i interesima Putnika, - Pre polaska na put dostavi ime, adresu i
                broj telefona lokalnog predstavnika, odnosno lokalne agencije partnera a ako toga nema naziv, adresu i broj telefona Organizatora za nužnu pomoć Putniku; -
                Ne odgovara za usluge pružene Putniku od strane drugih lica van Programa, - Sve usmene i bilo koje druge vrste informacije, koje se razlikuju od onih koje
                su sadržane u Programu, Ugovoru ili Posebnom ugovoru i ovim Opštim uslovima, ne obavezuju Organizatora i ne mogu biti osnov za isticanje prigovora ili
                reklamacije putnika.
            </p>
            <p dir="ltr">
                4. OBAVEZA I PRAVA PUTNIKA:
            </p>
            <p dir="ltr">
                - Da se detaljno upozna, kao i sva lica iz Ugovora, sa Programom i Opštim uslovima, da istakne posebne zahteve koji nisu obuhvaćeni objavljenim Programom,
            </p>
            <p dir="ltr">
                - Da sam obezbedi fakultativne polise putnog osiguranja, jer iste ne obezbeđuje i za njih ne odgovara Organizator,
            </p>
            <p dir="ltr">
                - Da plati ugovorenu cenu pod uslovima, rokovima i na način predviđen Ugovorom,
            </p>
            <p dir="ltr">
                - Da Organizatoru blagovremeno dostavi tačne i kompletne podatke i dokumenta potrebna za organizovanje putovanja i garantuje da on, njegove isprave,
                prtljag iI dr. ispunjavaju uslove određene propisima naše, tranzitne i odredišne zemlje (granični, carinski, sanitarni, monetarni i drugi propisi),
            </p>
            <p dir="ltr">
                - Da nadoknadi štetu koju pričini neposrednim pružaocima usluga ili trećim licima kršenjem zakonskih i drugih propisa i ovih Opštih uslova,
            </p>
            <p dir="ltr">
                - Da blagovremeno odredi drugo lice da umesto njega putuje, Organizatoru naknadi stvarne troškove prouzrokovane zamenom i da solidarno odgovara za
                neplaćeni deo ugovorene cene,
            </p>
            <p dir="ltr">
                - Da bez odlaganja na licu mesta opravdani prigovor saopšti po pravilu u pisanoj formi Organizatoru ili licima navedenim u putnoj dokumentaciji,
            </p>
            <p dir="ltr">
                - Da se pre zaključenja ugovora informiše preko sajta Ministarstva spoljnih poslova R. Srbije (www.msp.gov.rs) i na druge načine o zemljama tzv. visokog
                ili umerenog rizika;
            </p>
            <p dir="ltr">
                - Da se najkasnije 24 sata ali ne ranije od 48 sati informiše kod ovlašćenih predstavnika Organizatora o tačnom vremenu polaska i povratka sa putovanja.
            </p>
            <p dir="ltr">
                5. CENE I SADRŽAJ USLUGA:
            </p>
            <p dir="ltr">
                Cene su iskazane u stranoj valuti a obračun uplata vrši se u dinarima prema prodajnom kursu poslovne banke (Intesa banka) Organizatora na dan uplate,
                odnosno po kursu navedenom u Programu ili ako drugačije nije ugovoreno. Cene su formirane na osnovu poslovne politike Organizatora i ne mogu biti predmet
                prigovora Putnika. Usluge izvršene u inostranstvu (koje nisu unapred ugovorene i plaćene) Putnik plaća na licu mesta neposrednom izvršiocu usluge. Cena iz
                Ugovora uključuje, unapred pripremljenu i objavljenu kombinaciju najmanje dve ili više sledećih usluga prosečnog kvaliteta uobičajenog za datu destinaciju
                i objekte i to: smeštaja, ishrane, prevoza, pripreme i organizacije putovanja, za koje je ugovorena jedinstvena cena koju putnik plaća (dalje: Standardne
                usluge). Cena aranžmana ne uključuje, ako nešto drugo nije posebno ugovoreno (dalje: Poseban ugovor), troškove: aerodromskih i lučkih taksi, lokalnog
                turističkog vodiča, predstavnika organizatora, turističkog animatora, fakultativnih programa, korišćenja ležaljki i suncobrana, pribavljanja viza, ulaznica
                u objekte i na manifestacije, osiguranja putnika i prtljaga, usluga room service, korišćenja sobnog bara, klima uređaja, rekreativnih, lekarskih,
                telefonskih i dr. usluga, rezervaciju posebnog sedišta u prevoznom sredstvu, troškove smeštaja u jednokrevetnoj sobi, sobe sa posebnim karakteristikama
                (pogled, sprat, veličina, balkon itd), dodatni obroci i dr. (dalje: Posebne usluge). Posrednik nije ovlašćen da u ime Organizatora ugovara posebne usluge
                koje nisu predviđene Programom. Uslovi koji se odnose na ostvarivanje popusta za decu kao i na ostale pogodnosti koje su posebno date u Programu određeni
                su od neposrednih pružalaca usluga i iste treba tumačiti restriktivno (npr. za decu do dve godine starosti, relevantan je kalendarski datum kada dete
                navršava dve godine u odnosu na dan početka putovanja a ne datum zaključenja ugovora). U slučaju pogrešno navedene starosti putnika Organizator ima pravo
                da naplati razliku do korektne cene putovanja uz doplatu iznosa od 3.000,00 din za manipulativne troškove. U cenu nisu uključeni i Organizator ne može biti
                odgovoran Putniku za fakultativne i naknadno izvršene usluge, koje izvrši i naplati ino-partner, odnosno, neposredni pružalac usluga, a nisu bile
                predviđene Programom ili Posebnim ugovorom, kao i za učešće Putnika na sportskim i drugim slobodnim aktivnostima.
            </p>
            <p dir="ltr">
                6. PROMENA CENE I PRAVO PUTNIKA NA OTKAZ:
            </p>
            <p dir="ltr">
                Organizator može zahtevati povećanje ugovorene cene najkasnije 8 dana pre početka putovanja ako je nakon zaključenja Ugovora došlo do promene u kursu
                razmene valute, kada je cena izražena u dinarima ili do promene u tarifama prevoznika i u drugim zakonom predviđenim slučajevima. Za povećanje ugovorene
                cene do 10 % nije potrebna saglasnost putnika i nije osnov za raskid Ugovora. Ako povećanje ukupno ugovorene cene prelazi 10%, Putnik ima pravo da: zahteva
                zamenu za sličan Program bez doplate iz ponude Organizatora ili može putem pisanog otkaza raskinuti Ugovor bez obaveze naknade štete Organizatoru, ako
                najkasnije u roku od 48h od dostavljanja pisanog obaveštenja o povećanju cene, obavesti Organizatora. Ako u naznačenom roku, putnik pisanim putem ne
                obavesti organzatora da odustaje od ugovora, smatra se da je saglasan sa novom cenom, a što može biti i kroz izvršenu uplatu. Naknadna sniženja cena
                Programa ne mogu se odnositi na već zaključene Ugovore i ne mogu biti osnov bilo kakvog prigovora putnika prema Organizatoru.
            </p>
            <p dir="ltr">
                7. KATEGORIZACIJA I OPIS USLUGA:
            </p>
            <p dir="ltr">
                Sve usluge navedene u Programu podrazumevaju standardne usluge prosečnog kvaliteta, uobičajene i specifične za određene destinacije, mesta i objekte. U
                slučaju da putnik želi neke usluge van Programa, o tome mora zaključiti Poseban ugovor. Organizator ne odgovara za opise usluga u katalozima -
                publikacijama ili na web-sajtovima Posrednika i neposrednih pružalaca usluga (npr. hotela, prevoznika i dr. lica), osim ako Putnika nije izričito uputio na
                iste. Organizator odgovara samo za opise usluga sadržanih u svojim Programima, odnosno na svom web sajtu, s tim da očigledne štamparske i računske greške
                daju pravo Organizatoru na osporavanje Ugovora. Smeštajni objekti i smeštajne jedinice, prevozna sredstva i dr. usluge opisani su prema službenoj
                kategorizaciji domicilne zemlje u vreme objavljivanja Programa, različiti su i nisu uporedivi po destinacijama, pa ni u okviru iste destinacije. Ishrana,
                konfor i kvalitet usluge zavise prevashodno od cene aranžmana, izabrane destinacije i kategorizacije određene po lokalnim-nacionalnim propisima i van
                nadzora i uticaja su Organizatora. Datum početka i završetka putovanja utvrđen Programom ne podrazumeva celodnevni boravak putnika u smeštajnom objektu,
                odnosno destinaciji. Vreme polaska ili dolaska putnika i ulaska ili izlaska putnika iz smeštajnog objekta uslovljen je procedurama na graničnim prelazima,
                stanju na putevima, dozvolama nadležnih vlasti, tehničkim i vremenskim uslovima ili višom silom koje mogu da utiču na vreme polaska aviona i drugog
                prevoznog sredsta na koje organizator ne može uticati, te zbog toga za takve slučajeve Organizator ne snosi odgovornost. Prvi i poslednji dan iz Programa
                su predvidjeni za putovanje i ne podrazumevaju boravak u hotelu ili mestu opredeljenja - već samo označavaju kalendarski dan početka i završetka putovanja,
                tako da Organizator ne snosi odgovornost zbog večernjeg, noćnog ili ranog jutarnjeg leta, ulaska u sobu u kasnim večernjim časovima, napuštanja hotela u
                ranim jutarnjim časovima i slično. Za avio aranžmane ugovoreno vreme početka putovanja je sastanak putnika na aerodromu koji je najmanje 2 časa ranije u
                odnosu na prvo objavljeno vreme poletanja od strane avio-kompanije. U slučaju pomeranja navedenog vremena poletanja aviona Organizator ne snosi nikakvu
                odgovornost, već se primenjuju nacionalni i međunarodni propisi iz oblasti avio-saobraćaja. Po pravilu odlazak – dolazak, poletanje - sletanje aviona kod
                čarter letova je u kasnim večernjim ili ranim jutarnjim časovima i ako je npr. obezbeđen ugovoreni početni ili završni obrok u vidu tzv. “hladnog obroka”
                van ili u smeštajnom objektu, smatra se da je Ugovor u celosti izvršen. Usluge turističkog vodiča, pratioca, lokalnog vodiča, animatora ili lokalnog
                predstavnika ne podrazumeva njihovo celodnevno i kontinuirano prisustvo, već samo kontakt i neophodnu-nužnu pomoć Putniku po unapred utvrđenim terminima
                periodičnog dežurstva objavljenih na oglasnoj tabli ili na drugi prikladan način. Instrukcije i uputstva ovlašćenog predstavnika Organizatora (posebno u
                vezi sa vremenom polazaka, prevozom, smeštajem, zakonskihm i drugih propisa i dr.) obavezuju putnika a nepridržavanje pomenutih instrukcija predstavlja
                povredu Ugovora i sve eventualne posledice i štetu u takvom slučaju snosi Putnik u celosti.Promena ili odstupanja pojedinih usluga koje nisu prouzrokovane
                voljom Organizatora su dozvoljene ukoliko se ne odražavaju negativno na celokupni koncept ugovorenog putovanja. Ukoliko iz navedenih razloga, let ili
                prevoz treba da bude premešten na drugi aerodrom ili mesto, Organizator snosi sve troškove alternativnog prevoza najmanje u visini vozne karte 2. klase
                prevoza. Kad treće lice stupa na mesto lica koje je rezervisalo određenu turističku uslugu, Organizator ima pravo na naknadu za nastale potrebne troškove
                promene. Putnik i lice koje stupa na njegovo mesto solidarno odgovaraju za plaćanje ugovorene cene i troškove zamene putnika. Organizator neće prihvatiti
                zamenu putnika ako promena nije blagovremena, ako postoje posebni zahtevi u odnosu na putovanje ili nije u skladu sa zakonskom ili drugim pravnom
                regulativom.
            </p>
            <p dir="ltr">
                8. SMEŠTAJ, ISHRANA I PREVOZ:
            </p>
            <p dir="ltr">
                8.1. Smeštaj: Ako drugačije nije posebno ugovoreno:
            </p>
            <p dir="ltr">
                - Putnik će biti smešten u bilo koju službeno registrovanu smeštajnu jedinicu u smeštajnom objektu opisanom u Programu, bez obzira na osobenosti putnika,
                lokaciju i položaj objekta, spratnost, blizinu buke, parkinga i dr. katakteristike, - Smeštaj Putnika u objekat je najranije posle 16,00 h na dan početka
                korišćenja usluge, a napuštanje objekta najkasnije do 09,00 h na dan završetka korišćenja usluge. Putnik nema pravo na refundaciju zbog samovoljnog,
                odnosno svojom krivicom izazvanog povremenog ili prevremenog napuštanja smeštajnog objekta, ni na cenu hotelske usluge, ni na cenu prevoza, - Trokrevetne i
                četvorokrevetne smeštajne jedinice (sobe, studiji, apartmani i sl.) u skladu sa kategorizacijom i propisima domicilne zemlje su po pravilu na bazi
                standardne dvokrevetne sobe sa jednim, odnosno dva pomoćna ležaja, koji su po pravilu drvene ili metalne konstrukcije na rasklapanje i koji mogu bitno
                pogoršati kvalitet smeštaja, - Funkcionisanje klima uređaja u smeštajnim objektima različit je po destinacijama i objektima i ne podrazumeva neprekidan rad
                iste 24 časa, - Organizator ne odgovara Putniku za štetu nastalu zbog njegovog nepoštovanja zakonskih propisa, propisanih pravila i običaja utvrđenih od
                strane prevoznika, hotelijera i drugih neposrednih pružalaca usluga. - Ukoliko su dve ili više osoba rezervisale zajedno dvokrevetnu ili višekrevetnu sobu
                ili brodsku kabinu i sl. a nema treće osobe koja zamenjuje jednu od njih, Organizator ima pravo naplate pune cenu smeštajne jedinice. - Nakon otpočinjanja
                turističkog putovanja, a zbog iznenadnih i opravdanih razloga, ugovoreni smeštaj može se bez saglasnosti Putnika zameniti smeštajem u objektu iste ili više
                kategorije u ugovorenom mestu smeštaja na teret Organizatora, a smeštaj u objekte niže kategorije može se izvršiti uz saglasnost Putnika i povraćaja
                razlike u ceni srazmerno smanjenoj kategoriji smeštajnog objekta. - Putnik preuzima obavezu upoznavanja i poštovanja pravila ponašanja u smeštajnom objektu
                a naročito na: deponovanja i čuvanja novca, dragocenosti i vrednih stvari, unos hrane i pića u sobe, poštovanje reda, smeštaja i napuštanja sobe u određeno
                vreme, broj osoba u sobi i dr. jer Organizator ne odgovara za štete nastale po tom osnovu.
            </p>
            <p dir="ltr">
                8.2. Ishrana: Ako drugačije nije posebno ugovoreno: - Raznovrsnost, kvalitet hrane i servisa ishrane, zavisi pretežno od visine cene aranžmana, kategorije
                objekta, destinacije i lokalnih običaja bez obzira da li je usluživanje po principu samoposluživanje ili posluživanja (menija). - Usluga ALL INCLUSIVE i
                bilo koja druga podrazumeva usluge po internim hotelskim pravilima i ne mora biti identična ni u okviru iste kategorije na istoj destinaciji. Organizator
                je upoznao putnika sa sadržajem ALL INCLUSIVE usluge u pismenoj formi.
            </p>
            <p dir="ltr">
                - Doručak, ako drugačije nije naznačeno u Programu, podrazumeva kontinentalni doručak. - Ukoliko je popunjenost kapaciteta u hotelima ispod 30%, moguće je
                da se umesto usluge samoposluživanja uslugu ishrane izvrši posluživanjem. U smeštajnom objektu su identični uslovi ishrane, bez obzira da li po Ugovoru
                putuju deca, starija lica ili lica sa posebnim potrebama. U slučaju da na licu mesta Putnik sa neposrednim pružaocem ishrane postigne drugačiji dogovor,
                Organizator ne snosi nikakvu odgovornost za neadekvatno izvršenu usluge ishrane.
            </p>
            <p dir="ltr">
                8.3. Prevoz: Ako drugačije nije posebno ugovoreno: - Prevoz i transferi obavljaju se standardnim turističkim autobusima ili drugim sredstvima prema
                propisima i kriterijumima koji važe u zemlji u kojoj je registrovan prevoznik koga angažuje Organizator i primenjuju se propisi, principi i pravila
                određenih od strane prevoznika (npr. prevoz u bilo kom prevoznom sredstvu ne podrazumeva numerisana sedišta, niti uključen obrok i piće tokom putovanja
                itd.). Putnik ima obavezu da prihvati svako ponuđeno mesto u prevoznom sredstvu. - Organizator ima pravo da za prevoz angažuje sve tipove turističkih
                autobusa koji ispunjavaju uslove predviđene propisima (mini bus, autobus ili double decker), kao i druga prevozna sredstva ako to okolnosti uslovljavaju, -
                Za vreme vožnje u autobusima nisu u upotrebi toaleti, osim ukoliko to nije odobreno. Putnik je dužan da svu nastalu štetu svojom nepažnjom u prevoznom
                sredstvu nadoknadi na licu mesta. - Putnik ima obavezu primerenog ponašanja u prevoznom sredstvu i poštovanje sobraćajnih propisa i pravila o prevozu
                putnika, a u suprotnom Organizator ima pravo da ga ne primi na prevoz ili u prisustvu policije udalji iz prevoznog sredstva i dalji prevoz do odredišta
                neće biti obaveza Orgasnizatora. Ukoliko Putnik zbog udaljavanja iz prevoznog sredstva odustane od putovanja, primenjivaće se skala otkaza iz tačke 12.
                Opštih uslova. - Putni pravac, pauze, mesta i dužine njihovog trajanja određuje vodič - vozač. Vodič-vozač ima pravo da, zbog nepredvidivih, neižbežnih ili
                bezbedosnosnih i sličnih okolnosti, promeni red vožnje, itinerer puta, ili redosled obilazaka lokalitata.
            </p>
            <p dir="ltr">
                - Neusklađenost ličnih podataka datih organizatoru sa podacima u pasošu Putnika (imena putnika i dr.) mogu imati za posledicu ispisivanje nove avionske
                karte, uz troškove ili čak proglašenje karte neregularnom za šta posledice snosi Putnik. Putnik je odgovoran za svoju avionsku kartu od trenutka kada mu se
                uruči na aerodromu ili u agenciji. Ne postoji mogućnost izdavanja duplikata avionske karte, kao ni bording karte. Putnik u celosti snosi posledice njihovog
                gubitka ili nestanka tokom putovanja. - Avionske ili posebne prevozne karte važe samo na njima naznačenim datumima i vremenima. - Prevoz Putnika vazdušnim,
                železničkim, morskim, rečnim ili jezerskim prevoznim sredstvima obavlja se i direktna je odgovornost ovih prevoznika određena u skladu sa propisima i
                običajima kojima se regulišu pomenute vrste prevoza i van uticaja i odgvornosti su Organizatora.
            </p>
            <p dir="ltr">
                9. PUTNE ISPRAVE, ZDRAVSTVENI I ZAKONSKI PROPISI:
            </p>
            <p dir="ltr">
                Svi uslovi objavljeni u Programu odnose se isključivo na državljane sa putnom ispravom R. Srbije. Organizator ne snosi odgovornost i nije dužan upoznati
                putnike državljane drugih država na uslove (vizne, carinske, zdravstvene i dr.) koji važe za odredišnu ili tranzitnu zemlju, već je obaveza stranog
                državljanina da se informiše kod nadležnog konzulata i da Putnik sam potrebne uslove i isprave obezbedi blagovremeno i uredno. Putnik za putovanje u
                inostranstvo mora imati važeću putnu ispravu sa rokom važenja još najmanje 6 meseci od dana završetka putovanja i u roku dostaviti organizatoru ispravne i
                kompletne potrebne podatke i dokumenta za dobijanje vize, ukoliko istu pribavlja Organizator. Službenik agencije Organizatora, niti Posrednika nije
                ovlašćen da utvrdjuje validnost putnih i drugih isprava i dokumenata. Kada Organizator posreduje u postupku podnošenja dokumentacije isti ne garantuje
                dobijanje vize, niti dobijanje vize u roku i ne snosi nikakvu odgovornost za neispravnost putnog i drugih dokumenta ili ako pogranične vlasti ili
                imigracione službe ne odobre ulazak, tranzit ili dalji boravak Putniku. Ukoliko Putnik za vreme putovanja izgubi putne isprave ili mu budu ukradene, dužan
                je o svom trošku blagovremeno obezbediti nove i snositi sve eventualne štetne posledice po tom osnovu. Putnik je dužan ugovoriti Posebne usluge vezano za
                njegovo zdravstveno stanje, kao npr.specifična ishrana, karakteristike smeštaja itd. zbog hronične bolesti, alergije, invaliditeta i dr. jer u protivnom
                Organizator ne preuzima nikakvu posebnu obavezu, odgovornost ni štetu po tom osnovu. Za putovanja u zemlje, u kojima važe posebna pravila koja obuhvataju
                obaveznu vakcinaciju ili nabavku određenih dokumenata, obaveza je putnika da obavi potrebne vakcinacije i obezbedi odgovarajuće potvrde o tome i da u
                slučaju eventualnih posledica sam snosi odgovornost za štetu. Putnik je dužan striktno poštovati carinske, devizne i dr. propise R. Srbije, tranzitnih i
                zemalja u kojima boravi, te u slučaju nemogućnosti nastavka putovanja, odnosno boravka i svega drugog, sve posledice i troškove snosi sam putnik. Ukoliko
                se putovanje ne može realizovati zbog propusta putnika vezano za odredbe ove tačke, primenuju se odredbe tačke 12. Opštih uslova.
            </p>
            <p dir="ltr">
                10. PRTLJAG:
            </p>
            <p dir="ltr">
                Prevoz prtljaga do određene težine koju određuje avio prevoznik, je besplatan. Višak prtljaga Putnik plaća prema važećim cenama prevoznika. Transport
                specijalnog prtljaga od aerodroma do hotela i nazad je isključiva obaveza Putnika. Na svim aerodromima se primenjuju posebna bezbedonosna pravila u vezi sa
                ručnim prtljagom, te preporučujemo za više informacija da se putnik informiše na aerodromu Nikola Tesla u Beogradu na telefon 011/ 209 - 4444 ili web
                sajta: www.beg.aero. Štete i gubitak prtljaga na letovima Putnik je dužan da prijavi bez odlaganja na licu mesta nadležnoj aerodromskoj službi za
                izgubljeni prtljag, jer avio kompanije po pravilu odbijaju naknadu ako nije popunjen i predat formular za prijavu štete. Kod prevoza autobusom putnik može
                poneti 2 komada prtljaga po korisniku sedišta i predati ga ovlašćenom licu Organizatora. Deca do dve godine nemaju pravo na besplatan prtljag. Putnik je
                dužan voditi brigu o svojim stvarima unetim u prevozno sredstvo, o davanju, odnosno preuzimanju prtljaga predatog ovlašćenom licu prevoznika, odnosno
                unetom u smeštajni objekat. Sva svoja prava po navedenom, putnik ostvaruje direktno od prevoznika, pružaoca usluge smeštaja ili osiguranja a prema važećim
                međunarodnim i domaćim propisima. Prenos prtljaga od mesta parkiranja do smeštajne jedinice je obaveza putniika (prevoz će biti što je moguće bliže
                smeštajnom objektu). Za nestanak ili oštećenje prtljaga u transportu od parkinga do smeštajnog objekta, kao i za zaboravljene stvari u prevoznom sredstvu
                Organizator ne snosi odgovornost. Osim kod namere i grube nepažnje Organizator nema nikakvu odgovornost za prtljag i predmete, koji se obično ne nose sa
                sobom, izuzev kada je izričito preuzeo predmete na čuvanje. Zato se Putniku ne preporučuje, da na putovanje nosi vredne predmete, a u suprotnom da iste
                preda uredno na čuvanje ili da ih nose sa sobom. Dužnost putnika je da vidljivo označi svoj prtljag sa ličnim podacima, i da lične dokumenta, stvari i
                vrednosti ne ostavlja u parkiranom prevonom sredstvu, jer Organizator ne odgovara za njihov nestanak. Preporučuje se da se dokumeta, zlato, vredne stvari,
                tehnički instrumenti i medikamenti nose isključivo u ručnom prtljagu. Putnik ima obavezu da prijavi gubitak, oštećenja ili nestanak prtljaga u toku puta
                predstavniku Organizatora ili neposrednog izvršioca usluge.
            </p>
            <p dir="ltr">
                11. PROMENA I OTKAZ UGOVORA OD STRANE ORGANIZATORA:
            </p>
            <p dir="ltr">
                11.1. Pre početka putovanja: Organizator je dužan da Putnika obavesti o svakoj bitnoj promeni Programa na način na koji je zaključen Ugovor, najkasnije u
                roku od 5 dana pre početka putovanja, a Putnik ima rok od 48 časova od dana prijema obaveštenja o promeni odgovoriti Organizatoru da li prihvata istu.
                Prihvat nove ponude može se izvršiti i kroz izvršenu uplatu novougovorene cene. U slučaju prihvata nove ponude, Putnik ima pravo na srazmerno sniženje cene
                u slučaju da je nova ponuda niža od prvobitno ugovorene, odnosno ima obavezu uplatiti razliku u ceni između prvobitne i nove ponude, ukolika je ponuda viša
                od prvobitno ugovorene. Ukoliko ne prihvati nijednu alternativu ponuđenu od strane Organizatora, Putnik ima pravo na povraćaj ukupno uplaćene cene.
                Organizator ima pravo raskinuti Ugovor u slučaju: - nedovoljnog broja prijavljenih putnika, pod uslovom da je Putnika o tome obavestio najkasnije 5 dana
                pre početka turističkog putovanja i - zbog nemogućnosti ispunjenja ugovornih obaveza za koji nisu odgovorne ugovorne strane, a koje bi da su postojale u
                vreme objavljivanja Programa bile opravdan razlog Organizatoru da Program ne objavljuje i Ugovor ne zaključuje, uz obavezu da Putniku izvrši povraćaj
                uplaćenih sredstava najkasnije u roku od 15 dana od dana otkaza. Ukoliko u Programu nije posebno navedeno, da bi se putovanje realizovalo, najmanji broj
                prijavljenih putnika treba da bude: za putovanje autobusom 30 putnika, za putovanje na redovnim avio linijama u Evropi 20 putnika, za putovanje na
                interkontinentalnim avio linijama 15 putnika, za putovanje na posebno ugovorenim avio-čarter linijama, vozovima, hidrogliserima i dr.najmanje 80%
                popunjenosti kapaciteta po svakom prevoznom sredstvu. U slučaju prihvatanja novog ugovora Putnik se odriče bilo kakvih potraživanja prema Organizatoru po
                osnovu prvobitno zaključenog Ugovora.
            </p>
            <p dir="ltr">
                11.2. Za vreme putovanja: Organizator za vreme putovanja, o čemu je dužan bez odlaganja na najpogodniji način obavestiti Putnika, zadržava pravo promene
                dana ili sata putovanja, kao i pravo promene maršute putovanja i neophodne izmene Programa ukoliko se promene uslovi za putovanje (promenjen red letenja,
                prinudno sletanje, kvar prevoznog sredstva, gužva na granicama ili u saobraćaju, zatvaranje nekog od lokaliteta predviđenog za obilazak, promene u viznom
                režimu, bezbedonosna situacija, elementarne nepogode ili druge vanredne i objektivne okolnosti i više sile) bez obaveze isplate štete ili bilo kakve druge
                naknade putniku. U navedenim slučajevima Organizator sam snosi eventualne dodatne troškove izmene Programa. Organizator se oslobađa ispunjenja Ugovora
                onda, ako Putnik ometa sprovodjenje putovanja usled grubog i nedoličnog ponašanja, bez obzira na izrečenu opomenu. U tom slučaju putnik ima obavezu da
                organizatoru nadoknati pričinjenu eventualnu štetu. U slučaju nastupanja vanrednih okolnisti za vreme putovanja koje se unapred nisu mogle predvideti, a
                koji se mogu podvesti pod višu silu (terorističkih napada, vanrednog stanja, eksplozija, zaraze, epidemije i druge bolesti, elementarne nepogode, klimatski
                uslovi i sl.), obe ugovorne strane imaju pravo raskinuti Ugovor, pri čemu Organizator ima pravo na stvarne odnosno učinjene troškove i obavezu plaćanja
                polovine prevoznih troškova povratka Putnika. Organizator ne preuzima nikakvu odgvornost ako Putnik odbije ponuđeni povratak obezbeđenim prevoznim
                sredstvom.
            </p>
            <p dir="ltr">
                12. OTKAZ UGOVORA OD STRANE PUTNIKA:
            </p>
            <p dir="ltr">
                12.1. Pre početka putovanja: Putnik ima pravo da odustane od putovanja, o čemu je dužan pismeno izvestiti Organizatora na način kako je zaključen Ugovor.
                Datum pismenog otkaza Ugovora predstavlja osnov za obračun naknade koja pripada Organizatoru, izražene procentualno po skali otkaza u odnosu na ukupnu cenu
                putovanja, ako Programom nije drugačije određeno i to:
            </p>
            <p dir="ltr">
                5% ako se putovanje otkaže do 45 dan pre početka putovanja,
            </p>
            <p dir="ltr">
                10 % ako se putovanje otkaže od 44 do 30 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                20 % ako se otkaže 29 do 20 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                40 % ako se otkaže 19 do 15 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                80 % ako se otkaže 14 do 10 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                90 % ako se otkaže 9 do 6 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                100 % ako se otkaže 5 do 0 dana pre početka putovanja ili u toku putovanja.
            </p>
            <p dir="ltr">
                Izuzetno od napred navedenog, primenivaće se sledaća skala otkaza i to:
            </p>
            <p dir="ltr">
                a. kod brodskih krstarenja
            </p>
            <p dir="ltr">
                5% a najmanje 60,00 eur do 91 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                15% od 90 do 45 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                30% od 44 do 29 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                50%od 28 do 15 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                80% od 14 do 7 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                95% od 6 do 3. dana pre početka putovanja,
            </p>
            <p dir="ltr">
                100% na dan putovanja, nedolaska ili odustanka u toku puta
            </p>
            <p dir="ltr">
                b. za rekreativni odmor za predškolski uzrast, nastava u prirodi, đačke i studenske ekskurzije ako se otkazuje kompletan ugovor:
            </p>
            <p dir="ltr">
                5% ako se putovanje otkaže do 120 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                20 % ako se otkaže od 119 do 90 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                50 % ako se otkaže 0d 89 do 60 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                80 % ako se otkaže od 59 do 45 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                100 % ako se otkaže od 44 do pre početka ili u toku putovanja.
            </p>
            <p dir="ltr">
                Promena ugovorenog mesta, datuma putovanja, prevoznog sredstva, smeštajnog objekta, smeštajne jedinice, nedobijanje vize, neplaćanje ugovorene cene i sl.,
                smatra se odustajanjem putnika od putovanja. Putnik je u obavezi Organizatoru naknaditi samo stvarne, odnosno učinjene troškove (troškove prevoza,
                smeštaja, organizacije putovanja i sl.), ukoliko je do otkaza došlo zbog: iznenadne bolesti putnika, bračnog druga, deteta, roditelja, brata ili sestre
                putnika, usvojenika i usvojioca, smrti putnika, bračnog druga, deteta, roditelja, brata ili sestre putnika, usvojenika i usvojioca, - poziva za vojnu vežbu
                putnika ili elementarne nepogode ili vanrednog stanja zvanično proglašenih od nadležnog organa zemlje putovanja. Za navedene slučajeve Putnik je obavezan
                dostaviti Organizatoru dokaz kojim se ostvaruju prava iz zdravstvenog osiguranja po osnovu privremene sprečenosti za rad (potvrdu izabranog lekara iz
                oblasti opšte medicine, odnosno otpusnu listu stacionarne zdravstvene ustanove kojom se izričito potvrđuje iznenadna bolest i nemogućnost putovanja),
                odnosno umrlicu, odnosno poziv za vojnu vežbu. Ne mogu se smatrati opravdanim razlozima za otkaz ili prekid putovanja Putnika slučajevi lokalnih
                terorističkih napada, eksplozija, zaraze, epidemije i druge bolesti, elementarne nepogode, klimatski uslovi i sl., za koje nije proglašeno vanredno stanje
                od strane nadležnih državnih organa domicilne ili zemlje putovanja. Iznenadna bolest podrazumeva od strane ovlašćenog lekara utvrđeno iznenadno i
                neočekivano oboljenje, odnosno infektivnu bolest ili organski poremećaj, koji nastane posle zaključenja ugovora o putovanju i nije u vezi sa, niti je
                posledica nekog prethodnog zdravstvenog stanja, a takve je prirode da zahteva lečenje, boravak u bolnici (hospitalizaciju) i onemogućava početak
                -korišćenje ugovorenog putovanja. Organizator, u slučaju da Putnik obezbedi odgovarajuću zamenu ili pak zamenu izvrši sam Organizator, dužan je putniku
                izvršiti povraćaj uplaćenih sredstava u ukupnom iznosu, po odbitku samo stvarnih i učinjenih troškova. Organizator je u slučaju zamene putnika obavezan da
                sa novim putnikom zaključi Ugovor. U slučaju odustanka od putovanja koje je pokriveno polisom osiguranja, putnik svoje pravo ostvaruje direktno od
                osiguravača. Kod odustanka od Ugovora, putniku se ne vraća iznos plaćen Organizatoru za posredovanju u dobijanju viza, kao i plaćenih zakonskih i drugih
                obaveza.
            </p>
            <p dir="ltr">
                12.2. Nakon otpočinjanja putovanja: Ukoliko zbog otkaza putovanja Putnik svojom krivicom ne iskoristi neke od ugovorenih usluga, Organizator će pokušati da
                od davaoca usluga dobije naknadu na ime neiskorišćenih usluga. Ukoliko mu davalac usluga ne vrati novac, Putnik nema pravo na povraćaj odgovarajućeg dela
                cene neiskorišćenog putovanja. Ukoliko je u pitanju beznačajna usluga ili vrednost, Organizator se oslobađa ove obaveze. Ako se krivicom Organizatora ne
                obavlja znatan deo usluga koji su utvrdjeni Ugovorom, Organizator je dužan da sprovede odredjene preventivne mere kako bi se moglo nastaviti putovanje ili
                da ponudi Putniku druge odgovarajuće usluge do okončanja turističkog putovanja bez dodatnih troškova za Putnika, sve u skladu sa tačkom 14 ovih Optih
                uslova, ne dirajući ostala zakonska prava Putnika
            </p>
            <p dir="ltr">
                13. OSIGURANJE I GARANCIJA PUTOVANJA:
            </p>
            <p dir="ltr">
                U cenu putovanja nije uključeno putno osiguranje. Organizator savetuje zaključenje osiguranja za otkaz putovanja, osiguranje putne odgovornosti,
                zdravstveno osiguranje i osiguranje protiv nezgoda. Ukoliko Organizator i Posrednik nude putna osiguranja, radi se samo o posredovanju. Ugovor o osiguranju
                se zaključuje samo između Putnika i osiguravajuće kompanije, kome se eventualni zahtevi direktno upućuju. Treba da pročitate uslove osiguranja i obaveze iz
                ugovora o osiguranju. Premije osiguranja nisu sastavni deo cene putovanja i dospevaju odmah pri zaključivanju ugovora o osiguranju. Potpisivanjem Ugovora
                Putnik potvrđuje da mu je informisan i upućen na obezbeđenje paketa putnog osiguranja. Paket putnog osiguranja ne pokriva obavezno zdravstveno osiguranje,
                te se Putniku preporučuje da isto sam obezbedi, jer to može biti razlog da pogranične vlasti ne dozvole dalje putovanje ili da Putnik mora sam platiti
                značajne troškove eventualnog lečenja.
            </p>
            <p dir="ltr">
                Prema Zakonu o turizmu Organizator ima sledeće garancije putovanja i to:
            </p>
            <p dir="ltr">
                A - Za troškove nužnog smeštaja, ishrane i povratka putnika sa putovanja u mesto polaska u zemlji i inostranstvu usled insolventnosti Organizatora, polisu
                osiguranja br. 70002866, od 01.06.2014 god. osiguravajuće kompanije „KOMPANIJA DUNAV OSIGURANJE” iz BEOGRADA, ul Makedonska, br.4. Putnik zatečen na
                putovanju trebalo bi na najbrži način da kontaktira osiguravača, na tel. br. 0800386286, ili e.mail: <a href="mailto:info@dunav.com">info@dunav.com</a> .
                Putnik je obavezan da dostavi osiguravaču i Organizatoru broj ugovora, mesto putovanja, naziv smeštajnog objekta, imena putnika, adresu ili broj telefona,
                faxa ili e.mail preko kojih se može kontaktirati u mestu trenutnog boravka.)
            </p>
            <p dir="ltr">
                B - Za naknadu štete koja se prouzrokuje putniku neispunjenjem, delimičnim ispunjenjem ili neurednim ispunjenjem obaveza Organizatora, u skladu sa Opštim
                uslovima i Programom putovanja i to, polisu osiguranja br. 00029654 2, od 01.06.2014 god. osiguravajuće kompanije „KOMPANIJA DUNAV OSIGURANJE” iz BEOGRADA,
                ul Makedonska, br.4. i (Putnik svoja prava za naknadu štete ostvaruje na osnovu pravnosnanžne i izvršne sudske presude, odnosno odluke arbitražnog suda ili
                drugog vansudskog rešenja potrošačkog spora, u skladu sa ovim Opštim uslovima i Opštim uslovima YUTE.)
            </p>
            <p dir="ltr">
                Potpisivanjem Ugovora Putnik potvrdjuje da su mu uručeni opšti uslovi osiguranja i da iste u celosti prihvata.
            </p>
            <p dir="ltr">
                14. POMOĆ, PRIGOVOR, TUŽBA I REŠAVANJE SPOROVA:
            </p>
            <p dir="ltr">
                Putnik je obavezan bez odlaganja na licu mesta opravdani prigovor saopštiti lokalnom predstavniku Organizatora, a u hitnim slučajevima ako ovaj nije
                trenutno dostupan, neposrednom pružaocu usluge (npr. prevozniku, hotelijeru i dr.), ili ako ta lica nisu navedena u putnim dokumetima direktno
                Organizatoru. Za pomoć, hitne i druge slučajeve, kao i reklamacije Putnik može kontaktirati Organizatora preko tel. broja +381 11 334 6776, faksa +381 11
                334 6776, radnim danima od 0900h-2000h, subotom od 0900h-1500h po srednje evropskom vremenu ili preko e-maila: info@robinson.rs. Za hitne i slične postupke
                potrebno je da Putnik navede broj ugovora, mesto putovanja, naziv smeštajnog objekta, imena putnika, adresu ili broj telefona i dr. preko kojih se može
                kontaktirati. Putnik je u obavezi da dobronamerno sarađjuje i strpljivo sačeka vremenski okvir od 24-48 h da se opravdani prigovor na licu mesta otkloni
                (npr. kvar frižidera, nestanak struje ili vode, loše očišcćen apartman i dr. nedostaci) i prihvati ponuđeno rešenje koje odgovara ugovorenoj usluzi. Ako
                uzrok prigovora nije otklonjen na licu mesta, Putnik sa predstavnikom organizatora o tome sastavlja pisanu potvrdu u dva primerka koju obe strane
                sačinjavaju i potpisuju. Putnik zadržava jedan primerak ove potvrde. Ako je uzrok prigovora otklonjen na licu mesta, Putnik je obavezan potpisati potvrdu o
                istom, a u suprotnom činjenica da je nastavio korišćenje adekavtnog altermativnog rešenja smatra se da je Program u celosti izvršen. Lokalni predstavnici
                nemaju pravo da priznaju bilo kakve zahteve za naknadu, već isključivo Organizator. Putnik ne može da zahteva srazmerno sniženje cene, raskid Ugovora i
                naknadu štete ako nesavesno i na propisani način propusti da na licu mesta, bez odlaganja i blagovremeno obavesti ovlašćenog predstavika i Organizatora o
                nedostacima između pruženih i ugovorenih usluga. Ukoliko nedostaci nisu otklonjeni na licu mesta, Putnik je obavezan da u roku od osam dana od dana
                završetka putovanja, isključivo Organizatoru, dostavi osnovan i dokumentovan prigovor (pisani prigovor na licu mesta, račune o plaćenim troškovima, zahtev
                po vrstama neizvršenih usluga činjenično konkretizovan i kvantifikovan u odnosu na svakog putnika ponaosob, svedoke i druge dokaze) i zahtevati povraćaj
                razlike u ceni između ugovorenih i neizvršenih odnosno delimično izvršenih usluga. Svaki putnik potpisnik ugovora u svoje ime i u ime lica iz ugovora ili
                lica sa urednim punomoćjem za zastupanje, prigovor podnosi pojedinačno, jer organizator neće razmatrati grupne prigovore. Pritužbe i druge postupke Putnik
                je ovezan dostaviti u pisnaoj formi isključivo na adresu Organizatora u Beogradu, ul Beogradska 29. Organizator je dužan uzeti u postupak samo
                blagovremene, obrazložene i dokumentovane prigovore po učinjenoj reklamaciji Putnika, a kojima se uzrok nije mogao otkloniti u toku putovanja na licu
                mesta. Organizator je dužan u roku od 15 dana dostaviti putniku pisani odgovor i isplatiti razliku u ceni, sve od dana prijema urednog prigovora. Ukoliko
                prigovor nije kompletan i isti treba urediti, organizator će dostaviti putniku odgovor da istu u ostavljenom roku uredi pod pretnjom propuštanja.
                Organizator će u skladu sa dobrim poslovnim običajima u zakonskom roku odgovoriti putniku i po reklamacijama koje su neblagovremene, neosnovane ili
                neuredne. Sniženje cene po reklamaciji putnika može dostići samo iznos reklamiranog a neizvršenog dela usluge, ne može obuhvatiti već iskorisćene usluge,
                niti dostići iznos celokupne ugovorene cene. Visina naknade, koja se isplaćuje po osnovanom i blagovremenom prigovoru, srazmerna je stepenu neizvršene,
                odnosno delimično izvršene usluge. Ukoliko Putnik prihvati isplatu naknade na ime srazmernog sniženja cene, ili koji drugi vid naknade, podrazumeva se da
                je saglasan sa predlogom organizatora za mirno rešenje spora, te se na taj način odrekao svih daljih potraživanja prema Organizatoru u vezi spornog odnosa,
                bez obzira na činjenicu da li je o tome potpisao pismenu potvrdu o izvršenoj refundaciji sa klauzulom o konačnom razrešenju medjusobnih spornih odnosa.
                Smatraće se da je povraćaj razlike u ceni putniku izvršen i postignut dogovor sa putnikom u skladu sa zakonom, ovim Opštim uslovima i opštim uslovima YUTE,
                kada je Organizator putniku ponudio realnu razliku u ceni za neadekvatno pružene usluge, u skladu sa cenovnikom neposrednog pružaoca usluga koji je važio
                na dan zaključenja ugovora o putovanju, i drugim raspoloživim dokazima, te da je organizator postupio u skladu sa pozitivnim propisima. Organizator ne
                snosi odgvornost za propuste, odnosno za štetu nanetu Putniku od strane neposrednih pružaoca usluga koji odgovaraju saglasno propisima koji se na njih
                odnose, ako se ponašao kao pažljiv Organizator pri izboru lica koja su te usluge izvršila. Svaki zahtev Putnika za iniciranje postupka pred drugim licima
                pre isteka roka za rešavanje prigovora smatraće se preuranjenim kao i obaveštavanje javnih glasila i medija povredom Ugovora.
            </p>
            <p dir="ltr">
                15. PROGRAM PUTOVANJA PO ZAHTEVU PUTNIKA I POJEDINAČNE USLUGE:
            </p>
            <p dir="ltr">
                15.1. Program putovanja po zahtevu Putnika: Individualno putovanje (dalje: Program po zahtevu) Putnika jeste kombinacija dve ili više usluga, koji se ne
                nalazi u ponudi Organizatora, odnosno koji Organizator nije prethodno objavio, već ga je sačinio po zahtevu Putnika. Na Program po zahtevu analogno se
                primenjuju odredbe prethodnih tačaka ovih Opštih uslova, ako ovom tačkom nije drugačije regulisano. Ukoliko je po zahtevu Putnika kombinovano i ugovoreno
                vise pojedinačnih usluga iz ponude Organizatora (npr. let i kruzna tura itd.), naknada za storno se obračunava po pojedinačnoj usluzi i na kraju se sabira.
                Putnik ima pravo da odustane od Ugovora, o čemu je dužan pismeno izvestiti Organizatora. Datum pismenog otkaza Ugovora predstavlja osnov za obračun naknade
                koja pripada Organizatoru, izražene procentualno u odnosu na ukupnu cenu zahtevanog putovanja, ako Programom nije drugačije određeno i to:
            </p>
            <p dir="ltr">
                5% ako se putovanje otkaže do 60 dana pre početka putovanja (blagovremeni otkaz),
            </p>
            <p dir="ltr">
                15 % ako se putovanje otkaže od 60 do 30 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                20 % ako se otkaže 29 do 20 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                40 % ako se otkaže 19 do 15 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                80 % ako se otkaže 14 do 10 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                90 % ako se otkaže 9 do 6 dana pre početka putovanja,
            </p>
            <p dir="ltr">
                100 % ako se otkaže 5 dana pre početka putovanja ili u toku putovanja.
            </p>
            <p dir="ltr">
                15.2. Pojedinačne usluge i „Rezervacije na upit“: Ukoliko Putnik rezerviše ili ugovori samo jednu uslugu, Organizator nastupa samo kao posrednik tudje
                usluge (dalje: Posrednik usluge). Za individualne i »rezervacije na upit« Putnik polaže na ime troškova rezervacije depozit koji ne može biti manji od 50
                EUR u dinarskoj protivvrednosti po prodajnom kusru banke Organizatora na dan uplate. Ukoliko rezervacija bude prihvaćena od strane Putnika, depozit se
                uračunava u cenu usluge. Ukoliko rezervaciju Organizator ne potvdi u ugovorenom roku, depozit se u celosti vraća Putniku. Ako Putnik ne prihvati ponuđenu
                ili potvrđenu rezervaciju, a koja je u celosti u skladu sa zahtevima putnika, iznos depozita zadržava Organizator u celosti. Organizator, osim zbog svoje
                grube nepažnje i nemara, ne odgovara za nedostatke, materijalna i telesna oštećenja kod individualnih turističkih usluga po zahtevu putnika, za koje je on
                samo posrednik između Putnika i neposrednih pružaoca usluga (npr. pojedinačna usluga smeštaja, prevoza, ulaznice za sportske manifestacije, izlete, rent-a
                car i dr.). Dobijanjem dokaza o ugovorenoj pojedinačnoj usluzi stupaju na snagu ugovorni odnosi isključivo izmedju Putnika i svakog pojedinačnog pružaoca
                usluge. Kod pojedinačnih turističkih usluga primenuje se sledeća skala otakza, ako drugačije nije ugovreno:
            </p>
            <p dir="ltr">
                a. za hotelski smeštaj:
            </p>
            <p dir="ltr">
                do 30 dana pre početka putovanja 10%
            </p>
            <p dir="ltr">
                od 29. do 22 dana pre početka putovanja 15%
            </p>
            <p dir="ltr">
                od 21. do 8 dana pre početka putovanja 25%
            </p>
            <p dir="ltr">
                od 7 dana pre početka putovanja 50%
            </p>
            <p dir="ltr">
                od 6 dana do i nakon početka korišćenja 100% od cene
            </p>
            <p dir="ltr">
                b. za zakup apartmana po jedinici:
            </p>
            <p dir="ltr">
                do 45 dana pre početka putovanja 20%
            </p>
            <p dir="ltr">
                od 44. do 30. dana pre početka putovanja 50%
            </p>
            <p dir="ltr">
                od 29. dana pre početka putovanja 70% i
            </p>
            <p dir="ltr">
                od 15 dana do i nakon početka korišćenja 100%,
            </p>
            <p dir="ltr">
                c. ostale individualne usluge: Rezervisane pojedine usluge kao na primer ulaznice za koncerte, operu, pozorište, balove, karte / markice za prevoz (npr
                metro, voz, autobus), karte za trajekt, skipas, razgledanja, ulaznice za muzeje i pojedinačni transferi i dr. prilikom eventualnog otkaza Putniku se
                obračunavaju troškovi u visini cene ugvorene svake pojedinačne usluge. Kod ugovorene pojedinačne usluge prevoza u slučaju blagovremenog storniranja treba
                vratiti već primljene karte za linijske letove, železničke karte ili tikete za trajekte, jer se u suprotnom moraju zaračunati pune cene. U slučaju da je
                Putnik za odmor rezervisao stan, Organizator upozorava na mogućnost da mu zakupodavac pri predaji stana za odmor može tražiti odgovarajuću kauciju za
                sporedne trošove i eventualno nastalu štetu.
            </p>
            <p dir="ltr">
                16. ZAŠTITA LIČNIH PODATAKA PUTNIKA:
            </p>
            <p dir="ltr">
                Lični podaci putnika, koje isti daje dobrovoljno, predstavljaju poslovnu tajnu Organizatora. Putnik je saglasan da lične podatke Organizator može koristiti
                za realizaciju ugovorenog programa putovanja, pri čemu se ne mogu saopštavati adrese, mesto, vreme i cena putovanja i imena saputnika drugim licima, osim
                licima određenim posebnim propisima.
            </p>
            <p dir="ltr">
                17. OBAVEZNOST PRIMENE:
            </p>
            <p dir="ltr">
                Organizator može Pogramom ili Posebnim uslovima putovanja predvideti drugačije odredbe u odnosu na ove Opšte uslove, zbog posebnih uslova i pravila
                neposrednim pružaoci usluga, kao i za putovanja sa posebnim sadržajima (povodom održavanja sportskih, kongresnih i sličnih međunarodnih manifestacija i
                posebnim vidovima turizma - đački, lov i ribolov, ekstremni sportovi i dr.) i koji čine sastavni deo takvih Ugovora. Neefikasnost pojedinih odredbi Ugovora
                nema za posledicu neefikasnost čitavog Ugovora o putovanju, što važi i za ove Opšte uslove. Putnik i Organizator saglasno ugovaraju nadležnost Arbitražnog
                suda YUTA-e, Beograd, Kondina 14 za rešavanje međusobnih sporova, a u slučaju zakonom predviđene stvarne nadležnosti redovnog suda Putnik i Organizator
                ugovaraju mesnu nadležnost suda prema sedištu Organizatora, uz primenu ovih Opštih uslova, kao i Opštih uslova putovanja YUTE i propisa R. Srbije.
            </p>
            <br/>
            <p dir="ltr">
                Ovi Opšti uslovi važe od 01.06.2014.god. kojim danom prestaju da važe opšti uslovi objavljeni 01.06.2013. godine.
            </p>
            <br/>
            <br/>
            <br/>
            <br/>
            <p dir="ltr">
                M.P. __________________________
            </p>
            <p dir="ltr">
                Ljubiša Nešovanović
            </p>
            <p dir="ltr">
                direktor
            </p>
            <br/>
            <br/>
        </div>
    </div>
</div>