
<div class="admin package create">
    <form method="post" enctype="multipart/form-data">
        <div>
<?=(new \Robinson\Backend\Tag\MultiSelect('destinationId', $select, '-- Izaberi destinatciju --'))?>
        </div>
        <div>
            <input class="form-control" type="text" name="package" placeholder="Aranzman" required="required" />
        </div>
        <div>
            <input class="form-control" type="text" name="price" placeholder="Cena od:" required="required" />
        </div>
        <div>
            <textarea name="description" class="ckeditor" placeholder="Tekst" required="required"></textarea>
        </div>
        <div>
            <label for="pdf">Pdf:</label>
            <input type="file" id="pdf" accept="application/pdf" name="pdf" required="required" />
        </div>
        <div>
            <select class="form-control" name="status" required="required">

                <?php foreach(\Robinson\Backend\Models\Package::getStatusMessages() as $status => $message): ?>

                <option value="<?=$status?>"><?=$message?></option>

                <?php endforeach ?>

            </select>
        </div>
        <div>
            <h3>Tabovi:</h3>
            
            <?php foreach($tabs as $type => $title): ?>
            
            <div>
                <label for="tab-<?=$type?>"><?=$title?></label>
                <textarea name="tabs[<?=$type?>]" class="ckeditor" placeholder="<?=$this->escaper->escapeHtmlAttr($title)?>"></textarea>
            </div>
            
            <?php endforeach ?>
        </div>
        <div>
            <button class="btn btn-default btn-lg" name="submit">OK</button>
        </div>
    </form>
</div>