
<div class="admin package create">
    <form method="post" enctype="multipart/form-data">
        <fieldset>
            <legend>Osnovni podaci</legend>

            <div>
                <label>Destinacija aranzmana</label>
    <?=(new \Robinson\Backend\Tag\MultiSelect('destinationId', $select, '-- Izaberi destinatciju --'))?>
            </div>
            <div>
                <label>Tip smestaja</label>
                <?=$this->tag->selectStatic(array
                (
                    'type',
                    \Robinson\Backend\Models\Package::getTypeMessages(),
                    'class' => 'form-control',
                )) . PHP_EOL ?>
            </div>
            <div>
                <label for="package">Aranzman</label>
                <input class="form-control" id="package" type="text" name="package" placeholder="Aranzman" required="required" />
            </div>
            <div>
                <label for="price">Cena</label>
                <input class="form-control" id="price" type="text" name="price" placeholder="Cena od:" required="required" />
            </div>
            <div>
                <label for="description">Opis</label>
                <textarea name="description" id="description" class="ckeditor" required="required">Opis</textarea>
            </div>
            <div>
                <label for="visibility">Vidljivost</label>
                <select id="visibility" class="form-control" name="status" required="required">

                    <?php foreach(\Robinson\Backend\Models\Package::getStatusMessages() as $status => $message): ?>

                        <option value="<?=$status?>"><?=$message?></option>

                    <?php endforeach ?>

                </select>
            </div>
        </fieldset>
        <fieldset>
            <legend>Pdf</legend>
            <div class="file">
                <input type="file" id="pdf" accept="application/pdf" name="pdf" required="required" />
            </div>
        </fieldset>
        <fieldset>
            <legend>Pdf2</legend>
            <div class="file">
                <input type="file" id="pdf2" accept="application/pdf" name="pdf2" />
            </div>
        </fieldset>
        <fieldset>
            <div>
                <legend>Tabovi</legend>

                <?php foreach ($tabs as $type => $title): ?>

                <div>
                    <label for="tab-<?=$type?>"><?=$title?></label>
                    <textarea name="tabs[<?=$type?>]" class="ckeditor" placeholder="<?=$this->escaper->escapeHtmlAttr($title)?>"></textarea>
                </div>

                <?php endforeach ?>

            </div>
        </fieldset>
        <fieldset>
            <legend>Tagovi</legend>
            <div>
                <label for="date">Datum:</label>
                <?=$this->tag->textField(
                    array(
                        'special',
             //           'class' => 'datepicker',
                        'id' => 'date',
                        'data-date-format' => 'yyyy-mm-dd',
                    )
                ) . PHP_EOL ?>
            </div>
            <div class="tags">
                <ul>

                    <?php foreach($tags as $type => $tag): ?>

                        <li>

                            <?=\Phalcon\Tag::checkField(array
                            (
                                'tags[' . $type . ']',
                                'value' => $tag,
                                'id' => 'tag-' . $type,
                            ))?>

                            <label for="tag-<?=$type?>"><?=$tag?></label>
                        </li>

                    <?php endforeach ?>

                </ul>
            </div>
        </fieldset>
        <div>
            <button class="btn btn-default btn-lg" name="submit">OK</button>
        </div>
    </form>
</div>