
<div class="admin package update">
    <form method="post" enctype="multipart/form-data">
        <fieldset>
            <legend>Osnovni podaci</legend>
            <div>
            <label>Destinacija aranzmana</label>
    <?=(new \Robinson\Backend\Tag\MultiSelect('destinationId', $select, '-- Izaberi destinatciju --'))?>

            </div>
            <div>
                <label>Tip aranzmana</label>
                <?=$this->tag->selectStatic(array
                (
                    'type',
                    \Robinson\Backend\Models\Package::getTypeMessages(),
                    'class' => 'form-control',
                )) . PHP_EOL ?>
            </div>
            <div>
                <label for="package">Naziv aranzmana</label>
                <?=$this->tag->textField(array
                (
                    'package',
                    'class' => 'form-control',
                    'required' => 'required',
                    'id' => 'package',
                )) . PHP_EOL ?>
            </div>
            <div>
                <label for="price">Cena od</label>
                <?=$this->tag->textField(array
                (
                    'price',
                    'class' => 'form-control',
                    'required' => 'required',
                    'id' => 'price',
                )) . PHP_EOL ?>
            </div>
            <div>
                <label for="description">Opis</label>
                <?=$this->tag->textArea(array
                (
                    'description',
                    'class' => 'ckeditor',
                    'placeholder' => 'Tekst',
                    'required' => 'required',
                    'id' => 'description',
                )) . PHP_EOL ?>
            </div>
            <div>
                <label for="visibility">Vidljivost</label>
                <?=$this->tag->selectStatic(array
                (
                    'status',
                    'required' => 'required',
                    \Robinson\Backend\Models\Package::getStatusMessages(),
                    'class' => 'form-control',
                    'id' => 'visibility',
                )) . PHP_EOL ?>
            </div>
        </fieldset>
        <fieldset>
            <legend>Slike i pdf</legend>
            <ul style="list-style-type: none">
                <?php foreach ($package->getImages() as $image): ?>

                <li style="display:inline-block;margin:10px">
                    <img style="cursor:pointer" data-package-image-id="<?=$image->getImageId()?>" src="<?=$image->getResizedSrc() ?>" />

                    <div style="margin-top:10px">
                        <?=$this->tag->textField(array
                        (
                            'sort[' . $image->getImageId() . ']',
                            'length' => 2,
                            'maxsize' => 2,
                            'size' => 2,
                            'value' => $image->getSort(),
                            'required' => 'required',
                        ))?>

                        <?=$this->tag->textField(array
                        (
                            'title[' . $image->getImageId() . ']',
                            'size' => 30,
                            'value' => $image->getTitle(),
                            'required' => 'required',
                        ))?>
                    </div>

                </li>

                <?php endforeach ?>

            </ul>

            <div style="clear:left">
                <input type="file" name="files[]" multiple="multiple" accept="image/jpeg, image/png" />
            </div>
            <hr />
            <div>
                <h5>Trenutni PDF file: <?=$this->tag->linkTo(array(array
                (
                    'for' => 'admin-update',
                    'controller' => 'package',
                    'action' => 'pdfPreview',
                    'id' => $package->getPackageId(),
                ), $package->getPdf(), 'target' => '_blank')); ?>
                </h5>
                <div>
                    <label for="pdf">Zameni pdf:</label>
                    <input type="file" name="pdf" accept="application/pdf" />
                </div>
            </div>
            <!--<div>
                <h5>Pdf2 file: </h5>

                <?php if ($package->getPdf2()): ?>

                <a href="/admin/package/pdfPreview/<?=$package->getPackageId()?>?pdfType=2"><?=$package->getPdf2()?></a>

                <?php endif ?>
                <div>
                    <label for="pdf2">Zameni pdf2:</label>
                    <input type="file" name="pdf2" accept="application/pdf" />
                </div>
            </div>-->
        </fieldset>
        <fieldset>
            <legend>Tabovi</legend>
            <div>

                <?php foreach($tabs as $type => $title): ?>

                <div>
                    <label for="tab-<?=$type?>"><?=$title?></label>

                    <?=\Phalcon\Tag::textArea(array
                    (
                        'tabs[' . $type . ']',
                        'placeholder' => $title,
                        'class' => 'ckeditor',
                    )) . PHP_EOL?>

                </div>

                <?php endforeach ?>

            </div>
        </fieldset>
        <fieldset>
            <legend>Tagovi</legend>
            <div>
                <label for="date">Datum:</label>
                <?=$this->tag->textField(
                    array(
                        'special',
          //              'class' => 'datepicker',
                        'id' => 'date',
                        'placeholder' => 'Unesi datum',
                        'data-date-format' => 'yyyy-mm-dd',
                    )
                ) . PHP_EOL ?>
            </div>
            <div class="tags">
                <ul>

                    <?php foreach($tags as $type => $tag): ?>

                        <li>

                            <?=\Phalcon\Tag::checkField(array
                                (
                                    'tags[' . $type . ']',
                                    'value' => $tag,
                                    'id' => 'tag-' . $type,
                                ))?>

                            <label for="tag-<?=$type?>"><?=$tag?></label>
                        </li>

                    <?php endforeach ?>

                </ul>
            </div>
        </fieldset>
        <div>
            <button class="btn btn-default btn-lg" name="submit">OK</button>
        </div>
    </form>
</div>
<script type="text/javascript">
    $('document').ready(function()
    {
        $('img[data-package-image-id]').hover(function(e)
        {
            $(this).css('opacity', 0.5);
        }, function()
        {
            $(this).css('opacity', 1);
        });
        $('img[data-package-image-id]').on('click', function(e)
        {
           e.preventDefault();
           if (!confirm('Da li sigurno zelite da obrisete ovu sliku?')) {
               return false;
           }
           var that = $(this);
           $.post("<?=$this->url->get(array('for' => 'admin', 'controller' => 'package', 'action' => 'deleteImage'))?>", {id: $(this).data('package-image-id')}, function(response)
           {
               if(response.response)
               {
                   that.parent().remove();
               }
           });
        });
    });
</script>