
<div class="admin package update">
    <form method="post" enctype="multipart/form-data">
        <fieldset>
            <legend>Osnovni podaci</legend>
            <div>
            <label>Destinacija aranzmana</label>
    <?=(new \Robinson\Backend\Tag\MultiSelect('destinationId', $select, '-- Izaberi destinatciju --'))?>

            </div>

            <div>
                <label for="package">Naziv aranzmana</label>
                <?=$this->tag->textField(array
                (
                    'package',
                    'class' => 'form-control',
                    'required' => 'required',
                    'id' => 'package',
                )) . PHP_EOL ?>
            </div>
            <div>
                <label for="price">Cena od</label>
                <?=$this->tag->textField(array
                (
                    'price',
                    'class' => 'form-control',
                    'required' => 'required',
                    'id' => 'price',
                )) . PHP_EOL ?>
            </div>
            <div>
                <label for="description">Opis</label>
                <?=$this->tag->textArea(array
                (
                    'description',
                    'class' => 'ckeditor',
                    'placeholder' => 'Tekst',
                    'required' => 'required',
                    'id' => 'description',
                )) . PHP_EOL ?>
            </div>
            <div>
                <label for="visibility">Vidljivost</label>
                <?=$this->tag->selectStatic(array
                (
                    'status',
                    'required' => 'required',
                    \Robinson\Backend\Models\Package::getStatusMessages(),
                    'class' => 'form-control',
                    'id' => 'visibility',
                )) . PHP_EOL ?>
            </div>
        </fieldset>
        <fieldset>
            <legend>Slike i pdf</legend>
            <ul>
                <?php foreach ($package->getImages() as $image): ?>

                <li>
                    <img data-package-image-id="<?=$image->getImageId()?>" src="<?=$image->getResizedSrc() ?>" />

                    <?=$this->tag->textField(array
                    (
                        'sort[' . $image->getImageId() . ']',
                        'length' => 2,
                        'maxsize' => 2,
                        'size' => 2,
                        'value' => $image->getSort(),
                        'required' => 'required',
                    ))?>

                    <?=$this->tag->textField(array
                    (
                        'title[' . $image->getImageId() . ']',
                        'size' => 60,
                        'value' => $image->getTitle(),
                        'required' => 'required',
                    ))?>

                </li>

                <?php endforeach ?>

            </ul>

            <div>
                <input type="file" name="files[]" multiple="multiple" accept="image/jpeg, image/png" />
            </div>
            <div>
                <h5>Pdf file: <?=$this->tag->linkTo(array(array
                (
                    'for' => 'admin-update',
                    'controller' => 'package',
                    'action' => 'pdfPreview',
                    'id' => $package->getPackageId(),
                ), $package->getPdf(), 'target' => '_blank')); ?>
                </h5>
                <div>
                    <label for="pdf">Zameni pdf:</label>
                    <input type="file" name="pdf" accept="application/pdf" />
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Tabovi</legend>
            <div>

                <?php foreach($tabs as $type => $title): ?>

                <div>
                    <label for="tab-<?=$type?>"><?=$title?></label>

                    <?=\Phalcon\Tag::textArea(array
                    (
                        'tabs[' . $type . ']',
                        'placeholder' => $title,
                        'class' => 'ckeditor',
                    )) . PHP_EOL?>

                </div>

                <?php endforeach ?>

            </div>
        </fieldset>
        <fieldset>
            <legend>Tagovi</legend>
            <div class="tags">
                <ul>

                    <?php foreach($tags as $type => $tag): ?>

                        <li>

                            <?=\Phalcon\Tag::checkField(array
                                (
                                    'tags[' . $type . ']',
                                    'value' => $tag,
                                    'id' => 'tag-' . $type,
                                ))?>

                            <label for="tag-<?=$type?>"><?=$tag?></label>
                        </li>

                    <?php endforeach ?>

                </ul>
            </div>
        </fieldset>
        <div>
            <button class="btn btn-default btn-lg" name="submit">OK</button>
        </div>
    </form>
</div>
<script type="text/javascript">
    $('document').ready(function()
    {
        $('img[data-package-image-id]').hover(function(e)
        {
            $(this).css('border', '5px solid red');
        }, function()
        {
            $(this).css('border', 'none');
        });
        $('img[data-package-image-id]').on('click', function(e)
        {
           e.preventDefault();
           var that = $(this);
           $.post("<?=$this->url->get(array('for' => 'admin', 'controller' => 'package', 'action' => 'deleteImage'))?>", {id: $(this).data('package-image-id')}, function(response)
           {
               if(response.response)
               {
                   that.parent().remove();
               }
           });
        });
    });
</script>