<div id="index-contact" style="padding-bottom:50px">
    <div class="inner-site">
        <h1><?=$this->translate->query('Kontakt')?></h1>
        <?php if ($this->flashSession->has('success')): ?>

            <p class="successMessage"><?=$this->flashSession->getMessages('success')[0]?></p>
        <?php endif ?>


        <form action="" method="post" class="contact-form">
            <div>
                <input class="input-text" required="required" type="text" name="name" placeholder="<?=$this->translate->query('Vaši podaci')?>" />
            </div>
            <div>
                <input class="input-text" required="required" type="email" name="email" placeholder="Email" />
            </div>
            <div>
                <input class="input-text" required="required" type="text" name="phone" placeholder="<?=$this->translate->query('Telefon')?>" />
            <div>
                <textarea class="input-textarea" required="required" placeholder="<?=$this->translate->query('Poruka')?>" name="body"></textarea>
            </div>
            <div>
                <input class="input-submit" type="submit" name="send" value="<?=$this->translate->query('Pošalji rezervaciju')?>" />
            </div>
        </form>
    </div>
</div>