<div id="index-index">
    <div class="inner-site">

        <?php if ($lastMinutePackages->count()): ?>

        <div id="index-last-minute">
            <h4>Specijalne ponude</h4>

            <?php foreach ($lastMinutePackages as $package): ?>

                <?php include __DIR__ . '/../partials/index-package-item.phtml' ?>

            <?php endforeach ?>

        </div>

        <?php endif ?>

        <?php if ($homepagePackages->count()): ?>

            <div id="index-first-minute">
                <!--<h4>Specijalne <strong>first minute</strong> ponude</h4>-->

                <?php foreach ($homepagePackages as $package): ?>

                    <?php include __DIR__ . '/../partials/index-package-item.phtml' ?>

                <?php endforeach ?>

            </div>

        <?php endif ?>

        <div id="index-first-section" class="index section tabs">
            <ul class="tabs-heading">
                <li><a href="#tab1" class="selected">AKTUELNE PONUDE</a></li>
                <li><a href="#tab2">NOVO U PONUDI</a></li>
            </ul>
            <div id="tab1">

                <?php foreach ($hotPackages as $package): ?>

                    <?php include __DIR__ . '/../partials/index-package-item.phtml' ?>

                <?php endforeach ?>

            </div>
            <div id="tab2">

                <?php foreach ($popularPackages as $package): ?>

                    <?php include __DIR__ . '/../partials/index-package-item.phtml' ?>

                <?php endforeach ?>

            </div>
        </div>

        <?php /* unfortunatly, i was requsted to remove this section ... will leave it under comment, in controller too ...
        <div id="index-category-tabs-section" class="index section tabs">
            <ul class="tabs-nav">
                <?php $i = 1; foreach ($topTabs as $key => $tab): ?>

                    <li><a href="#category-tab-<?=$key?>"<?=($i === 1) ? ' class="selected first-cat"' : ''?>><?=$tab->name?></a></li>
                <?php $i++; endforeach ?>

            </ul>

            <?php foreach ($topTabs as $key => $tab): ?>

            <div class="category-tab" id="category-tab-<?=$key?>">


                <?php if (isset($tab->category->images[0])): ?>

                <div class="cat-thumb">
                    <?=\Phalcon\Tag::image($tab->category->images[0]->getResizedSrc()) . PHP_EOL ?>
                </div>
                <?php endif ?>


                <div class="cat-text">

                    <?=$tab->category->getDescription(200) . PHP_EOL ?>

                </div>

            </div>

            <?php endforeach ?>

        </div>
        */ ?>

        <div id="index-category-links-section" class="index section tabs">
            <ul class="tabs-heading">

                <?php $i = 1; foreach ($bottomTabs as $key => $tab): ?>

                    <li><a href="#category-link-tab-<?=$key?>"<?=($i === 1) ? ' class="selected"' : ''?>><?=mb_strtoupper($tab->name)?></a></li>

                <?php $i++; endforeach ?>

            </ul>

            <?php foreach ($bottomTabs as $key => $tab): ?>

                <div class="package-tab" id="category-link-tab-<?=$key?>">

                    <?php foreach ($tab->packages as $package): ?>
                        <?php include __DIR__ . '/../partials/index-package-item.phtml' ?>

                    <?php endforeach ?>

                </div>

            <?php endforeach ?>

        </div>
    </div>
</div>
