<?php
$this->assets->collection('bootstrap-js')
    ->addJs('http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js', false, false);
$this->assets->collection('bootstrap-css')
    ->addCss('http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css', false, false);

$this->assets->collection('css')
    ->addCss(APPLICATION_PATH . '/../public/css/css.css')
    ->setTargetPath(APPLICATION_PATH . '/../public/min/final-backend.css')
    ->setTargetUri('min/final-backend.css')
    ->addFilter(new \Phalcon\Assets\Filters\Cssmin());

$this->assets
    ->collection('jquery')
    ->addJs('http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js', false, false);


$this->assets->collection('ckeditor')
    ->addJs('_ckeditor/ckeditor.js')
    ->addJs('_ckeditor/adapters/jquery.js')
    ->join(false)
    ->setTargetPath(APPLICATION_PATH . '/../public/min/ckeditor-backend.js')
    ->setTargetUri('min/ckeditor-backend.js')
    ->addFilter(new \Phalcon\Assets\Filters\Jsmin());
?>
<!DOCTYPE html>
<html>
	<head>
		<?=$this->tag->getTitle() . PHP_EOL ?>
                <meta charset="utf-8" />

                <?=$this->assets->outputJs('jquery') . PHP_EOL ?>
                <?=$this->assets->outputJs('bootstrap-js')?>
                <?=$this->assets->outputCss('bootstrap-css')?>
                <?=$this->assets->outputJs('ckeditor') . PHP_EOL ?>
                <?=$this->assets->outputCss('css') . PHP_EOL ?>

                <script type="text/javascript">
                    $('.ckeditor').ckeditor();
                </script>
                <style type="text/css">
                    .admin.category.create div, .admin.category.update div {margin-top:10px}
                </style>
	</head>
	<body>
            <?=(new \Robinson\Backend\Tag\MainMenu())->mainMenu() . PHP_EOL ?>
            <?=$this->getContent() . PHP_EOL ?>
	</body>
</html>