<?php 
$this->assets
    ->addJs('http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js', false, false)
    ->addJs('http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js', false, false);

$jsManager = new \Phalcon\Assets\Manager();
$jsManager->collection('mainjs')
    ->addJs('_ckeditor/ckeditor.js', true, true)
    ->addJs('_ckeditor/adapters/jquery.js', true, true)
    ->join(false)
    ->setTargetPath('js/js.js')
    ->setTargetUri('js/js.js')
    ->addFilter(new \Phalcon\Assets\Filters\Jsmin());
?>
<!DOCTYPE html>
<html>
	<head>
		<?=$this->tag->getTitle() . PHP_EOL ?>
                <?=$this->assets->outputCss() . PHP_EOL ?>
                <?=$this->assets->outputJs() . PHP_EOL ?>
                <?=$jsManager->outputJs('mainjs') . PHP_EOL ?>
                <script type="text/javascript">
                    $('.ckeditor').ckeditor();
                </script>
	</head>
	<body>
            <?=(new \Robinson\Backend\Tag\MainMenu())->mainMenu() . PHP_EOL ?>
            <?=$this->getContent() . PHP_EOL ?>
	</body>
</html>