
<div class="admin destination create">
    <form method="post">
        <fieldset>
            <legend>Osnovni podaci</legend>
                <div>
                    <select class="form-control" name="categoryId" required="required">
                        <option value="">-- Izaberi kategoriju --</option>

                        <?php foreach($categories as $category): ?>

                        <option value="<?=$category->getCategoryId()?>"><?=$category->getCategory()?></option>

                        <?php endforeach ?>

                    </select>
                </div>
                <div>
                    <input class="form-control" type="text" name="destination" placeholder="Destinacija" required="required" />
                </div>
                <div>
                    <textarea name="description" class="ckeditor" placeholder="Tekst" required="required">Opis</textarea>
                </div>

                <div>
                    <label for="status">Vidljivost</label>
                    <select class="form-control" name="status" id="status" required="required">

                        <?php foreach(\Robinson\Backend\Models\Destination::getStatusMessages() as $status => $message): ?>

                        <option value="<?=$status?>"><?=$message?></option>

                        <?php endforeach ?>

                    </select>
                </div>
        </fieldset>
        <fieldset>
            <legend>Tabovi</legend>
            <div class="no-margin">

                <?php foreach($tabs as $type => $title): ?>

                <div>
                    <label for="tab-<?=$type?>"><?=$title?></label>
                    <textarea name="tabs[<?=$type?>]" class="ckeditor" placeholder="<?=$this->escaper->escapeHtmlAttr($title)?>"></textarea>
                </div>

                <?php endforeach ?>
            </div>
        </fieldset>
        <div>
            <button class="btn btn-default btn-lg" name="submit">OK</button>
        </div>
    </form>
</div>