
<div class="admin destination index">
    <form>
        <?=$this->tag->select(array
        (
            'categoryId',
            $categories,
            'using' => array('categoryId', 'category'),
            'useEmpty' => true,
            'emptyText' => '-- Izaberi kategoriju --',
        ))?>
    </form>
    
    <?php if ($destinations): ?>
    
    <h3>Destinacije:</h3>
    <ul>
        
        <?php foreach ($destinations as $destination): ?>
        
        <li><?=$this->tag->linkTo(array
        (
            array
            (
                'for' => 'admin-update',
                'controller' => 'destination',
                'action' => 'update',
                'id' => $destination->getDestinationId(),
            ),
            $destination->getDestination(),
            'style' => ($destination->isNotVisible()) ? 'text-decoration: line-through' : '',
        ))?></li>
        
        <?php endforeach ?>
        
    </ul>
    
    <?php endif ?>
    
    <p><?=$this->tag->linkTo(array
    (
        array
        (
            'for' => 'admin',
            'controller' => 'destination',
            'action' => 'create',
        ),
        'Dodaj novu destinaciju',
    ))?></p>
<script type="text/javascript">
    $('select').on('change', function(elem)
    {
        $('form').trigger('submit');
    });
</script>