
<div class="admin destination update">
    <form method="post">
        <div>
            
            <?=$this->tag->select(array
            (
                'categoryId',
                $categories,
                'using' => array('categoryId', 'category'),
                'required' => 'required',
                'class' => 'form-control',
            )) . PHP_EOL ?>
        </div>
        <div>
            <?=$this->tag->textField(array
            (
                'destination',
                'class' => 'form-control',
                'required' => 'required',
            )) . PHP_EOL ?>
        </div>
        <div>
            <?=$this->tag->textArea(array
            (
                'description',
                'class' => 'ckeditor',
                'placeholder' => 'Tekst',
                'required' => 'required',
            )) . PHP_EOL ?>
        </div>
        <div>
            <?=$this->tag->selectStatic(array
            (
                'status',
                'required' => 'required',
                \Robinson\Backend\Models\Destinations::getStatusMessages(),
                'class' => 'form-control',
            )) . PHP_EOL ?>
        </div>
        <div>
            <button class="btn btn-default btn-lg" name="submit">OK</button>
        </div>
    </form>
</div>