
<div class="admin destination update">
    <form method="post" enctype="multipart/form-data">
        <div>
            
            <?=$this->tag->select(array
            (
                'categoryId',
                $categories,
                'using' => array('categoryId', 'category'),
                'required' => 'required',
                'class' => 'form-control',
            )) . PHP_EOL ?>
        </div>
        <div>
            <?=$this->tag->textField(array
            (
                'destination',
                'class' => 'form-control',
                'required' => 'required',
            )) . PHP_EOL ?>
        </div>
        <div>
            <?=$this->tag->textArea(array
            (
                'description',
                'class' => 'ckeditor',
                'placeholder' => 'Tekst',
                'required' => 'required',
            )) . PHP_EOL ?>
        </div>
        <div>
            <?=$this->tag->selectStatic(array
            (
                'status',
                'required' => 'required',
                \Robinson\Backend\Models\Destinations::getStatusMessages(),
                'class' => 'form-control',
            )) . PHP_EOL ?>
        </div>
        <dl>
            <dt>Slike:</dt>
            
            <?php foreach($destination->getImages() as $image): ?>
            
            <dd>
                <img data-image-category-id="<?=$image->getDestinationImageId()?>" src="<?=$image->getResizedSrc() ?>" />
                
                <?=$this->tag->textField(array
                (
                    'sort[' . $image->getDestinationImageId() . ']',
                    'length' => 2,
                    'maxsize' => 2,
                    'size' => 2,
                    'value' => $image->getSort(),
                ))?>
                
            </dd>
            
        <?php endforeach ?>
            
        </dl>
        <div>
            <input type="file" name="files[]" multiple="multiple" accept="image/jpeg, image/png" />
        </div>
        <div>
            <button class="btn btn-default btn-lg" name="submit">OK</button>
        </div>
    </form>
</div>