
<div class="admin destination update">
    <form method="post" enctype="multipart/form-data">
        <fieldset>
            <legend for="category">Osnovni podaci</legend>
            <div>
                <label>Kategorija destinacije</label>
                <?=$this->tag->select(array
                (
                    'categoryId',
                    $categories,
                    'using' => array('categoryId', 'category'),
                    'required' => 'required',
                    'class' => 'form-control',
                    'id' => 'category',
                )) . PHP_EOL ?>
            </div>
            <div>
                <label for="destination">Destinacija</label>
                <?=$this->tag->textField(array
                (
                    'destination',
                    'class' => 'form-control',
                    'required' => 'required',
                    'id' => 'destination',
                )) . PHP_EOL ?>
            </div>
            <div>
                <label for="description">Opis</label>
                <?=$this->tag->textArea(array
                (
                    'description',
                    'class' => 'ckeditor',
                    'placeholder' => 'Tekst',
                    'required' => 'required',
                    'id' => 'description',
                )) . PHP_EOL ?>
            </div>
            <div>
                <label for="visibility">Vidljivost</label>
                <?=$this->tag->selectStatic(array
                (
                    'status',
                    'required' => 'required',
                    \Robinson\Backend\Models\Destination::getStatusMessages(),
                    'class' => 'form-control',
                )) . PHP_EOL ?>
            </div>
        </fieldset>
        <fieldset>
            <legend>Slike</legend>

            <ul>
                <?php foreach($destination->getImages() as $image): ?>

                <li style="display:inline-block; margin:10px; list-style-type: none">
                    <img style="cursor: pointer" data-destination-image-id="<?=$image->getImageId()?>" src="<?=$image->getResizedSrc() ?>" />

                    <div style="margin-top:10px">
                        <?=$this->tag->textField(array
                        (
                            'sort[' . $image->getImageId() . ']',
                            'length' => 2,
                            'maxsize' => 2,
                            'size' => 2,
                            'value' => $image->getSort(),
                        ))?>
                    </div>
                </li>

            <?php endforeach ?>

            </ul>

            <div>
                <input type="file" name="files[]" multiple="multiple" accept="image/jpeg, image/png" />
            </div>
        </fieldset>
        <fieldset>
            <legend>Tabovi</legend>
            <div>

                <?php foreach($tabs as $type => $title): ?>

                <div>
                    <label for="tab-<?=$type?>"><?=$title?></label>

                    <?=\Phalcon\Tag::textArea(array
                    (
                        'tabs[' . $type . ']',
                        'placeholder' => $title,
                        'class' => 'ckeditor',
                    )) . PHP_EOL?>

                </div>

                <?php endforeach ?>

            </div>
        </fieldset>
        <div>
            <button class="btn btn-default btn-lg" name="submit">OK</button>
        </div>
    </form>
</div>
<script type="text/javascript">
    $('document').ready(function()
    {
        $('img[data-destination-image-id]').hover(function(e)
        {
            $(this).css('opacity', 0.5);
        }, function()
        {
            $(this).css('opacity', 1);
        });

        $('img[data-destination-image-id]').on('click', function(e)
        {
           e.preventDefault();
           var that = $(this);
           if (!confirm('Da li sigurno zelite da obrisete ovu sliku?')) {
               return false;
           }
           $.post("<?=$this->url->get(array('for' => 'admin', 'controller' => 'destination', 'action' => 'deleteImage'))?>", {id: $(this).data('destination-image-id')}, function(response)
           {
               if(response.response)
               {
                   that.parent().remove();
               }
           });
        });
    });
</script>