<div class="admin category create">
    <form method="post">
        <div>
            <input type="text" name="category" placeholder="Kategorija" required="required" />
        </div>
        <div>
            <textarea name="description" placeholder="Tekst" required="required"></textarea>
        </div>
        <div>
            <select name="status" required="required">

                <?php foreach(\Robinson\Backend\Models\Category::getStatusMessages() as $status => $message): ?>

                <option value="<?=$status?>"><?=$message?></option>

                <?php endforeach ?>

            </select>
        </div>
        <div>
            <input type="submit" name="submit" value="OK" />
        </div>
    </form>
</div>