<div class="admin category create">
    <form method="post">
        <div>
            <input class="form-control" type="text" name="category" placeholder="Kategorija" required="required" />
        </div>
        <div>
            <textarea name="description" class="ckeditor" placeholder="Tekst" required="required"></textarea>
        </div>
        <div>
            <select class="form-control" name="status" required="required">

                <?php foreach(\Robinson\Backend\Models\Category::getStatusMessages() as $status => $message): ?>

                <option value="<?=$status?>"><?=$message?></option>

                <?php endforeach ?>

            </select>
        </div>
        <div>
            <button class="btn btn-default btn-lg" name="submit">OK</button>
        </div>
    </form>
</div>