
<div class="admin category index">
    <dl>
        <dt><h4>Kategorije</h4></dt>
        <dd>
            <ul class="nav nav-list">

                <?php foreach($categories as $category): ?>

                <li>
                    <?=$this->tag->linkTo(array
                    (
                        $category->getUpdateUrl(true),
                        $category->getCategory(),
                        'style' => ($category->getStatus()) ? 'text-decoration:line-through' : '', 
                    ))?>
                </li>
                <?php endforeach ?>

                <li><a href="<?=$this->url->get(array('for' => 'admin', 'controller' => 'category', 'action' => 'create'))?>">Dodaj novu kategoriju</a></li>

            </ul>
        </dd>
    </dl>
</div>