<div class="admin category update">
    <form method="post" enctype="multipart/form-data">
        <fieldset>
            <legend>Osnovni podaci</legend>
            <div>
                <label for="category">Kategorija</label>
                <?=$this->tag->textField(array
                (
                    'category',
                    'placeholder' => 'Kategorija',
                    'required' => 'required',
                    'value' => $category->getCategory(),
                    'class' => 'form-control',
                    'id' => 'category',
                ))
                ?>

            </div>
            <div>
                <label for="description">Opis</label>
                <?=$this->tag->textArea(array
                (
                    'description',
                    'placeholder' => 'Tekst',
                    'required' => 'required',
                    'class' => 'ckeditor form-control',
                    'id' => 'description',
                ))
                ?>

            </div>
            <div>
                <label for="visibility">Vidljivost</label>
                <?=$this->tag->selectStatic(array
                (
                    'status',
                    'required' => 'required',
                     \Robinson\Backend\Models\Category::getStatusMessages(),
                    'class' => 'form-control',
                    'id' => 'visibility',
                ))
                ?>
            </div>
        </fieldset>
        <fieldset>
            <legend>Slike</legend>
            <ul>

                <?php foreach($category->getImages() as $image): ?>

                <li>
                    <img data-image-category-id="<?=$image->getImageId()?>" src="<?=$image->getResizedSrc() ?>" />

                    <?=$this->tag->textField(array
                    (
                        'sort[' . $image->getImageId() . ']',
                        'length' => 2,
                        'maxsize' => 2,
                        'size' => 2,
                        'value' => $image->getSort(),
                    ))?>

                </li>

            <?php endforeach ?>

            </ul>
            <div>
                <input type="file" name="files[]" multiple="multiple" accept="image/jpeg, image/png" />
            </div>
            
        </fieldset>



        <div>
            <button class="btn btn-default btn-lg" name="submit">OK</button>
        </div>
    </form>
</div>
<script type="text/javascript">
    $('document').ready(function()
    {
        $('img[data-image-category-id]').hover(function(e)
        {
            $(this).css('border', '5px solid red');
        }, function()
        {
            $(this).css('border', 'none');
        });
        
        $('img[data-image-category-id]').on('click', function(e)
        {
           e.preventDefault();
           var that = $(this);
           $.post("<?=$this->url->get(array('for' => 'admin', 'controller' => 'category', 'action' => 'deleteImage'))?>", {id: $(this).data('image-category-id')}, function(response)
           {
               if(response.response)
               {
                   that.parent().remove();
               }
           });
        });
    });
</script>