<div class="admin category update">
    <form method="post" enctype="multipart/form-data">
        <div>
            
            <?=$this->tag->textField(array
            (
                'category',
                'placeholder' => 'Kategorija',
                'required' => 'required',
                'value' => $category->getCategory(),
            ))
            ?>

        </div>
        <div>
            <?=$this->tag->textArea(array
            (
                'description',
                'placeholder' => 'Tekst',
                'required' => 'required',
                'class' => 'ckeditor',
            ))
            ?>

        </div>
        <div>
            
            <?=$this->tag->selectStatic(array
            (
                'status',
                'required' => 'required',
                 \Robinson\Backend\Models\Category::getStatusMessages(),
            ))
            ?>
            
        </div>
        <dl>
            <dt>Slike:</dt>
            
            <?php foreach($category->getImages() as $image): ?>
            
            <dd>
                <img data-image-category-id="<?=$image->getImageCategoryId()?>" src="<?=$image->getResizedSrc() ?>" />
                
                <?=$this->tag->textField(array
                (
                    'sort[' . $image->getImageCategoryId() . ']',
                    'length' => 2,
                    'maxsize' => 2,
                    'size' => 2,
                    'value' => $image->getSort(),
                ))?>
                
            </dd>
            
        <?php endforeach ?>
            
        </dl>
        <div>
            <input type="file" name="files[]" multiple="multiple" accept="image/jpeg, image/png" />
        </div>

        <div>
            <input type="submit" name="submit" value="OK" />
        </div>
    </form>
</div>
<script type="text/javascript">
    $('document').ready(function()
    {
        $('img[data-image-category-id]').on('click', function(e)
        {
           e.preventDefault();
           var that = $(this);
           $.post("<?=$this->url->get(array('for' => 'admin', 'controller' => 'category', 'action' => 'deleteImage'))?>", {id: $(this).data('image-category-id')}, function(response)
           {
               if(response.response)
               {
                   that.parent().remove();
               }
           });
        });
    });
</script>